<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModularPipelines.DotNet" />
    <PackageReference Include="ModularPipelines.GitHub" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Respire.Pipeline.Tests" />
  </ItemGroup>

</Project>
