<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="..\..\src\Respire.Azure\Respire.Azure.csproj" />
    <ProjectReference Include="..\..\src\Respire.DependencyInjection\Respire.DependencyInjection.csproj" />
  </ItemGroup>
</Project>
