using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Respire.Analyzers.GeneratedModelBuilder;

namespace Respire.Analyzers;

/// <summary>Generates reflection-free JSON codecs, metadata, keys and typed property operations.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class RespireJsonGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidModel = new(
        DiagnosticIds.InvalidGeneratedJson, "Unsupported JSON model", "{0}", DiagnosticIds.Category,
        DiagnosticSeverity.Error, isEnabledByDefault: true,
        helpLinkUri: "https://thomhurst.github.io/Respire/docs/guides/generated-json-mappers");

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName("Respire.Json.RespireJsonAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (attribute, token) => Build((INamedTypeSymbol)attribute.TargetSymbol,
                attribute.Attributes[0], token, json: true)).WithTrackingName("RespireJsonModels");
        context.RegisterSourceOutput(models, static (output, model) =>
        {
            if (model.Error is not null)
                output.ReportDiagnostic(Diagnostic.Create(InvalidModel,
                    Location.Create(model.Path, model.Span, model.LineSpan), model.Error));
            else
                output.AddSource(model.HintName!, SourceText.From(model.Source!, Encoding.UTF8));
        });
    }

    internal static string JsonName(IPropertySymbol property) =>
        property.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonPropertyNameAttribute")
            ?.ConstructorArguments.FirstOrDefault().Value as string ?? property.Name;

    internal static string Render(INamedTypeSymbol type, string mapper, IPropertySymbol[] properties,
        IMethodSymbol constructor, string key)
    {
        var model = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        if (!type.ContainingNamespace.IsGlobalNamespace)
            source.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).Append(" {\n");
        source.Append(type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal")
            .Append(" static class ").Append(mapper).Append("\n{\n")
            .Append("    private static readonly global::System.Text.Json.JsonSerializerOptions Options = new() { TypeInfoResolver = global::System.Text.Json.Serialization.Metadata.JsonTypeInfoResolver.Combine() };\n")
            .Append("    public static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<").Append(model).Append("> JsonTypeInfo { get; } = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<")
            .Append(model).Append(">(Options, new ModelConverter());\n")
            .Append("    public static global::Respire.RespireKey GetKey(").Append(model).Append(" value)\n    {\n")
            .Append("        global::System.ArgumentNullException.ThrowIfNull(value);\n        return new global::Respire.RespireKey(").Append(key).Append(");\n    }\n")
            .Append("    private static string RequiredValue(string? value, string name) => value ?? throw new global::System.ArgumentException(\"Null required model property: \" + name, \"value\");\n")
            .Append("    private static global::Respire.Json.RespireJsonClient RequiredClient(global::Respire.Json.RespireJsonClient client) => client ?? throw new global::System.ArgumentNullException(nameof(client));\n")
            .Append("    public static byte[] ToJson(").Append(model).Append("? value) => global::System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(value!, JsonTypeInfo);\n")
            .Append("    public static ").Append(model).Append("? FromJson(global::System.ReadOnlySpan<byte> json) => global::System.Text.Json.JsonSerializer.Deserialize(json, JsonTypeInfo);\n")
            .Append("    public static global::System.Threading.Tasks.ValueTask<global::Respire.Json.RespireJsonValue<").Append(model).Append(">> GetAsync(global::Respire.Json.RespireJsonClient client, global::Respire.RespireKey key, global::System.Threading.CancellationToken cancellationToken = default)\n")
            .Append("        => RequiredClient(client).GetAsync(key, JsonTypeInfo, global::Respire.Json.RespireJsonPath.JsonPathRoot, cancellationToken);\n")
            .Append("    public static global::System.Threading.Tasks.ValueTask<bool> SetAsync(global::Respire.Json.RespireJsonClient client, ").Append(model)
            .Append(" value, global::Respire.Json.RespireJsonSetCondition condition = global::Respire.Json.RespireJsonSetCondition.None, global::System.Threading.CancellationToken cancellationToken = default)\n")
            .Append("        => SetAsync(client, GetKey(value), value, condition, cancellationToken);\n")
            .Append("    public static global::System.Threading.Tasks.ValueTask<bool> SetAsync(global::Respire.Json.RespireJsonClient client, global::Respire.RespireKey key, ").Append(model)
            .Append("? value, global::Respire.Json.RespireJsonSetCondition condition = global::Respire.Json.RespireJsonSetCondition.None, global::System.Threading.CancellationToken cancellationToken = default)\n")
            .Append("        => RequiredClient(client).SetAsync(key, value!, JsonTypeInfo, global::Respire.Json.RespireJsonPath.JsonPathRoot, condition, cancellationToken);\n");

        for (var index = 0; index < properties.Length; index++)
        {
            var property = properties[index];
            var propertyType = TypeName(property.Type);
            // RedisJSON escapes quotes/backslashes but expects literal Unicode and control characters.
            var path = "$[\"" + EscapePathName(JsonName(property)) + "\"]";
            source.Append("    private static readonly global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<").Append(propertyType).Append("> PropertyInfo")
                .Append(index).Append(" = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<").Append(propertyType)
                .Append(">(Options, new PropertyConverter").Append(index).Append("());\n")
                .Append("    public static global::Respire.Json.RespireJsonPath ").Append(property.Name).Append("Path { get; } = new(")
                .Append(Literal(path)).Append(");\n")
                .Append("    public static global::System.Threading.Tasks.ValueTask<global::Respire.Json.RespireJsonValue<").Append(propertyType).Append(">> Get").Append(property.Name)
                .Append("Async(global::Respire.Json.RespireJsonClient client, global::Respire.RespireKey key, global::System.Threading.CancellationToken cancellationToken = default)\n")
                .Append("        => RequiredClient(client).GetAsync(key, PropertyInfo").Append(index).Append(", ").Append(property.Name).Append("Path, cancellationToken);\n")
                .Append("    public static global::System.Threading.Tasks.ValueTask<bool> Set").Append(property.Name)
                .Append("Async(global::Respire.Json.RespireJsonClient client, global::Respire.RespireKey key, ").Append(propertyType)
                .Append(" value, global::System.Threading.CancellationToken cancellationToken = default)\n")
                .Append("        => RequiredClient(client).SetAsync(key, value, PropertyInfo").Append(index).Append(", ").Append(property.Name)
                .Append("Path, cancellationToken: cancellationToken);\n");
        }

        source.Append("    private sealed class ModelConverter : global::System.Text.Json.Serialization.JsonConverter<").Append(model).Append(">\n    {\n")
            .Append("        public override bool HandleNull => true;\n")
            .Append("        public override ").Append(model).Append(" Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)\n        {\n")
            .Append("            if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null) return null!;\n")
            .Append("            if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject) throw new global::System.Text.Json.JsonException(\"Expected a JSON object.\");\n");
        for (var index = 0; index < properties.Length; index++)
        {
            source.Append("            ").Append(TypeName(properties[index].Type)).Append(" field").Append(index).Append(" = default!;\n");
            if (!IsNullable(properties[index].Type)) source.Append("            bool found").Append(index).Append(" = false;\n");
        }
        source.Append("            while (reader.Read() && reader.TokenType != global::System.Text.Json.JsonTokenType.EndObject)\n            {\n")
            .Append("                if (reader.TokenType != global::System.Text.Json.JsonTokenType.PropertyName) throw new global::System.Text.Json.JsonException();\n")
            .Append("                var name = reader.GetString();\n                if (!reader.Read()) throw new global::System.Text.Json.JsonException();\n")
            .Append("                switch (name)\n                {\n");
        for (var index = 0; index < properties.Length; index++)
        {
            source.Append("                    case ").Append(Literal(JsonName(properties[index]))).Append(":\n")
                .Append("                        field").Append(index).Append(" = global::System.Text.Json.JsonSerializer.Deserialize(ref reader, PropertyInfo").Append(index).Append(")!;\n");
            if (!IsNullable(properties[index].Type)) source.Append("                        found").Append(index).Append(" = true;\n");
            source.Append("                        break;\n");
        }
        source.Append("                    default: reader.Skip(); break;\n                }\n            }\n")
            .Append("            if (reader.TokenType != global::System.Text.Json.JsonTokenType.EndObject) throw new global::System.Text.Json.JsonException();\n");
        for (var index = 0; index < properties.Length; index++)
            if (!IsNullable(properties[index].Type)) source.Append("            if (!found").Append(index)
                .Append(") throw new global::System.Text.Json.JsonException(").Append(Literal("Missing required JSON property: " + JsonName(properties[index]))).Append(");\n");
        var bound = constructor.Parameters.Select(parameter => Array.FindIndex(properties,
            property => property.Name.Equals(parameter.Name, StringComparison.OrdinalIgnoreCase))).ToArray();
        source.Append("            return new ").Append(model).Append('(')
            .Append(string.Join(", ", bound.Select(index => "field" + index))).Append(")\n            {\n");
        for (var index = 0; index < properties.Length; index++)
            if (!bound.Contains(index) || properties[index].IsRequired && !SetsRequiredMembers(constructor))
                source.Append("                @").Append(properties[index].Name).Append(" = field").Append(index).Append(",\n");
        source.Append("            };\n        }\n")
            .Append("        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ").Append(model).Append(" value, global::System.Text.Json.JsonSerializerOptions options)\n        {\n")
            .Append("            if (value is null) { writer.WriteNullValue(); return; }\n            writer.WriteStartObject();\n");
        for (var index = 0; index < properties.Length; index++)
            source.Append("            writer.WritePropertyName(").Append(Literal(JsonName(properties[index]))).Append(");\n")
                .Append("            global::System.Text.Json.JsonSerializer.Serialize(writer, value.@").Append(properties[index].Name)
                .Append(", PropertyInfo").Append(index).Append(");\n");
        source.Append("            writer.WriteEndObject();\n        }\n    }\n");
        for (var index = 0; index < properties.Length; index++) RenderPropertyConverter(source, properties[index], index);
        source.Append("}\n");
        if (!type.ContainingNamespace.IsGlobalNamespace) source.Append("}\n");
        return source.ToString();
    }

    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));

    private static string EscapePathName(string value)
    {
        var escaped = new StringBuilder();
        foreach (var character in value)
            switch (character)
            {
                case '\\': escaped.Append("\\\\"); break;
                case '"': escaped.Append("\\\""); break;
                default: escaped.Append(character); break;
            }
        return escaped.ToString();
    }

    private static void RenderPropertyConverter(StringBuilder source, IPropertySymbol property, int index)
    {
        var type = TypeName(property.Type);
        var kind = ScalarKind(property.Type)!;
        var read = kind switch
        {
            "String" => "reader.GetString()!",
            "Boolean" => "reader.GetBoolean()",
            "Double" => "reader.TryGetDouble(out var scalar) && global::System.Double.IsFinite(scalar) ? scalar : throw new global::System.Text.Json.JsonException(\"Invalid scalar JSON value.\")",
            _ => "reader.TryGet" + kind + "(out var scalar) ? scalar : throw new global::System.Text.Json.JsonException(\"Invalid scalar JSON value.\")",
        };
        var write = kind switch
        {
            "String" or "Guid" or "DateTimeOffset" => "WriteStringValue",
            "Boolean" => "WriteBooleanValue",
            _ => "WriteNumberValue",
        };
        source.Append("    private sealed class PropertyConverter").Append(index).Append(" : global::System.Text.Json.Serialization.JsonConverter<").Append(type).Append(">\n    {\n")
            .Append("        public override bool HandleNull => true;\n")
            .Append("        public override ").Append(type).Append(" Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)\n        {\n")
            .Append("            if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null) ");
        if (IsNullable(property.Type)) source.Append("return null;\n");
        else source.Append("throw new global::System.Text.Json.JsonException(").Append(Literal("Null required JSON property: " + JsonName(property))).Append(");\n");
        var expectedToken = kind switch
        {
            "String" or "Guid" or "DateTimeOffset" => "reader.TokenType != global::System.Text.Json.JsonTokenType.String",
            "Boolean" => "reader.TokenType != global::System.Text.Json.JsonTokenType.True && reader.TokenType != global::System.Text.Json.JsonTokenType.False",
            _ => "reader.TokenType != global::System.Text.Json.JsonTokenType.Number",
        };
        source.Append("            if (").Append(expectedToken).Append(") throw new global::System.Text.Json.JsonException(\"Unexpected scalar JSON token.\");\n");
        source.Append("            return ").Append(read).Append(";\n        }\n")
            .Append("        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ").Append(type).Append(" value, global::System.Text.Json.JsonSerializerOptions options)\n        {\n");
        if (IsNullable(property.Type))
            source.Append("            if (value is null) { writer.WriteNullValue(); return; }\n");
        else if (kind == "String") source.Append("            if (value is null) throw new global::System.Text.Json.JsonException(").Append(Literal("Null required JSON property: " + JsonName(property))).Append(");\n");
        var value = IsNullable(property.Type) && property.Type.IsValueType ? "value.Value" : "value";
        source.Append("            writer.").Append(write).Append('(').Append(value).Append(");\n        }\n    }\n");
    }
}
