using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Respire.Analyzers;

/// <summary>Emits directly constructible, reflection-free implementations of command interfaces.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class RespireCommandGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidDeclaration = new(
        DiagnosticIds.InvalidGeneratedCommand, "Unsupported generated command declaration", "{0}",
        DiagnosticIds.Category, DiagnosticSeverity.Error, isEnabledByDefault: true,
        helpLinkUri: "https://thomhurst.github.io/Respire/docs/guides/generated-commands");

    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers
            | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
            | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    internal const string ModelStepName = "RespireCommandInterfaces";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The transform projects each interface into rendered source plus location-free diagnostic data.
        // The model is value-equatable and holds no symbols, so unchanged interfaces skip the output step
        // and the pipeline never roots a Compilation between runs.
        var interfaces = context.SyntaxProvider.ForAttributeWithMetadataName(
                "Respire.RespireCommandsAttribute",
                static (node, _) => node is InterfaceDeclarationSyntax,
                static (attribute, cancellationToken) => Build((INamedTypeSymbol)attribute.TargetSymbol,
                    attribute.SemanticModel.Compilation, cancellationToken))
            .WithTrackingName(ModelStepName);
        context.RegisterSourceOutput(interfaces, static (output, model) => Emit(output, model));
    }

    private static void Emit(SourceProductionContext context, GeneratedInterface model)
    {
        foreach (var diagnostic in model.Diagnostics)
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        if (model.HintName is not null && model.Source is not null)
            context.AddSource(model.HintName, SourceText.From(model.Source, Encoding.UTF8));
    }

    private static GeneratedInterface Build(INamedTypeSymbol type, Compilation compilation, CancellationToken cancellationToken)
    {
        if (type.ContainingType is not null || type.Arity != 0 || type.Interfaces.Length != 0
            || type.IsFileLocal || type.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
        {
            return GeneratedInterface.Failed(type, "Command interfaces must be public or internal, top-level, non-generic, and have no base interfaces.");
        }

        var methods = type.GetMembers().OfType<IMethodSymbol>().ToArray();
        if (type.GetMembers().Any(member => member is not IMethodSymbol))
            return GeneratedInterface.Failed(type, "Command interfaces can contain only attributed abstract instance methods.");

        var errors = new List<DiagnosticInfo>();
        foreach (var method in methods)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var error = ValidateMethod(method, compilation);
            if (error is not null) errors.Add(DiagnosticInfo.Create(method, error));
        }
        if (errors.Count != 0) return new GeneratedInterface(null, null, errors.ToArray());

        var className = type.Name + "Implementation";
        if (type.ContainingNamespace.GetTypeMembers(className).Length != 0)
            return GeneratedInterface.Failed(type, $"Generated type '{className}' already exists in this namespace.");

        if (methods.Any(method => method.Name == className))
            return GeneratedInterface.Failed(type, "A command method cannot have the same name as its generated implementation class.");
        var memberNames = new HashSet<string>(methods.Select(method => method.Name)
            .Concat(methods.SelectMany(method => method.Parameters).Select(parameter => parameter.Name)), StringComparer.Ordinal);
        var clientField = LocalName(memberNames, "__client");
        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        if (!type.ContainingNamespace.IsGlobalNamespace)
            source.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).Append(" {\n");
        source.Append("/// <inheritdoc/>\n");
        source.Append(type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal")
            .Append(" sealed class ").Append(className).Append(" : ").Append(TypeName(type)).Append("\n{\n")
            .Append("    private readonly global::Respire.IRespireClient ").Append(clientField).Append(";\n")
            .Append("    /// <summary>Creates the generated command implementation.</summary>\n")
            .Append("    public ").Append(className).Append("(global::Respire.IRespireClient client)\n")
            .Append("    { this.").Append(clientField).Append(" = client ?? throw new global::System.ArgumentNullException(nameof(client)); }\n");

        for (var index = 0; index < methods.Length; index++)
            EmitMethod(source, methods[index], clientField, LocalName(memberNames, "__command" + index), compilation);
        source.Append("}\n");
        if (!type.ContainingNamespace.IsGlobalNamespace) source.Append("}\n");
        // Full metadata identity prevents collisions between equal simple names in distinct namespaces.
        return new GeneratedInterface(type.ToDisplayString().Replace("@", "") + ".Respire.g.cs", source.ToString(), []);
    }

    private static string? ValidateMethod(IMethodSymbol method, Compilation compilation)
    {
        if (method.MethodKind != MethodKind.Ordinary || method.IsStatic || !method.IsAbstract
            || method.Arity != 0 || method.ReturnsByRef || method.ReturnsByRefReadonly
            || method.DeclaredAccessibility != Accessibility.Public)
            return "Commands must be public, abstract, non-generic instance methods without ref returns.";

        var attribute = CommandAttribute(method);
        if (attribute is null || attribute.ConstructorArguments.Length != 1
            || attribute.ConstructorArguments[0].Value is not string name || name.Length == 0
            || name.Any(character => character < ' ' || character > '~'))
            return "Each method needs [RespireCommand] with a non-empty printable ASCII command name.";
        if (name.Contains(' '))
        {
            if (name[0] == ' ' || name[name.Length - 1] == ' ' || name.Contains("  ")
                || ResolveCatalogCommand(compilation, name) is null)
                return "Multi-token [RespireCommand] names must match a catalog command with single spaces between tokens.";
            if (attribute.NamedArguments.Any(argument => argument.Key == "Mutation"))
                return "Catalog subcommands use their descriptor's cache mutation metadata; omit Mutation.";
        }

        if (method.ReturnType is not INamedTypeSymbol task || !IsTask(task)
            || task.TypeArguments.Length > 1
            || (task.TypeArguments.Length == 1 && !IsReply(task.TypeArguments[0])))
            return "Return Task or ValueTask, optionally of RespireResult, string, byte[], bool, int, long, double, nullable scalars, or an array of these scalars.";

        var cancellationCount = 0;
        var flagsCount = 0;
        foreach (var parameter in method.Parameters)
        {
            if (parameter.RefKind != RefKind.None)
                return "Command parameters cannot use ref, in, or out.";
            if (IsCancellation(parameter.Type)) cancellationCount++;
            else if (IsFlags(parameter.Type)) flagsCount++;
            else if (!IsArgument(parameter.Type))
                return $"Unsupported argument type '{parameter.Type.ToDisplayString()}'; use RespireValue or an array of supported scalar arguments.";
        }
        return cancellationCount > 1 || flagsCount > 1
            ? "A command can declare at most one CancellationToken and one RespireCommandFlags parameter."
            : null;
    }

    private static AttributeData? CommandAttribute(IMethodSymbol method)
        => method.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.ToDisplayString() == "Respire.RespireCommandAttribute");

    private static string? CacheMutation(IMethodSymbol method)
    {
        var attribute = CommandAttribute(method);
        if (attribute is null) return null;
        foreach (var argument in attribute.NamedArguments)
        {
            if (argument.Key != "Mutation" || argument.Value.Type is not INamedTypeSymbol enumType) continue;
            foreach (var member in enumType.GetMembers())
            {
                if (member is IFieldSymbol { HasConstantValue: true } field
                    && Equals(field.ConstantValue, argument.Value.Value))
                {
                    return field.Name;
                }
            }
        }

        return null;
    }

    private static bool IsTask(INamedTypeSymbol type)
        => type.ContainingNamespace.ToDisplayString() == "System.Threading.Tasks"
            && (type.Name is "Task" or "ValueTask");

    private static bool IsCancellation(ITypeSymbol type)
        => type.ToDisplayString() == "System.Threading.CancellationToken";

    private static bool IsFlags(ITypeSymbol type)
        => type.ToDisplayString() == "Respire.RespireCommandFlags";

    private static bool IsBytes(ITypeSymbol type)
        => type is IArrayTypeSymbol { Rank: 1, ElementType.SpecialType: SpecialType.System_Byte };

    private static bool IsArgument(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array && !IsBytes(type))
            return array.Rank == 1 && IsScalarArgument(array.ElementType);
        return IsScalarArgument(type);
    }

    private static bool IsScalarArgument(ITypeSymbol type)
        => IsBytes(type) || type.SpecialType is SpecialType.System_String or SpecialType.System_Boolean
            or SpecialType.System_Char or SpecialType.System_Byte or SpecialType.System_SByte
            or SpecialType.System_Int16 or SpecialType.System_UInt16 or SpecialType.System_Int32
            or SpecialType.System_UInt32 or SpecialType.System_Int64 or SpecialType.System_UInt64
            or SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Decimal
            || type.ToDisplayString() is "Respire.RespireValue" or "Respire.RespireKey" or "System.Guid"
                or "System.DateTimeOffset" or "System.TimeSpan" or "System.ReadOnlyMemory<byte>"
                or "System.Memory<byte>" or "System.ArraySegment<byte>";

    private static ITypeSymbol UnwrapNullable(ITypeSymbol type)
        => type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable
            ? nullable.TypeArguments[0] : type;

    private static bool IsScalarReply(ITypeSymbol type)
    {
        type = UnwrapNullable(type);
        return IsBytes(type) || type.SpecialType is SpecialType.System_String or SpecialType.System_Boolean
            or SpecialType.System_Int32 or SpecialType.System_Int64 or SpecialType.System_Double;
    }

    private static bool IsReply(ITypeSymbol type)
        => type.ToDisplayString() == "Respire.RespireResult" || IsScalarReply(type)
            || type is IArrayTypeSymbol { Rank: 1 } array && IsScalarReply(array.ElementType);

    private static void EmitMethod(StringBuilder source, IMethodSymbol method, string clientField, string commandField,
        Compilation compilation)
    {
        var command = (string)CommandAttribute(method)!.ConstructorArguments[0].Value!;
        var catalogCommand = command.Contains(' ') ? ResolveCatalogCommand(compilation, command) : null;
        var task = (INamedTypeSymbol)method.ReturnType;
        var reply = task.TypeArguments.FirstOrDefault();
        var raw = reply?.ToDisplayString() == "Respire.RespireResult";
        var direct = raw && task.Name == "ValueTask";
        var arguments = method.Parameters.Where(parameter => !IsCancellation(parameter.Type) && !IsFlags(parameter.Type)).ToArray();
        var expanded = arguments.Where(parameter => parameter.Type is IArrayTypeSymbol && !IsBytes(parameter.Type)).ToArray();
        var cancellation = method.Parameters.FirstOrDefault(parameter => IsCancellation(parameter.Type));
        var flags = method.Parameters.FirstOrDefault(parameter => IsFlags(parameter.Type));
        var hidesObjectMember = method.Name is "Equals" or "Finalize" or "GetHashCode" or "GetType"
            or "MemberwiseClone" or "ReferenceEquals" or "ToString";

        source.Append("    private static readonly global::Respire.RespireCommand ").Append(commandField).Append(" = ");
        if (catalogCommand is not null)
            source.Append(catalogCommand.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Append('.').Append(Escape(catalogCommand.Name));
        else
            source.Append("global::Respire.RespireCommand.Create(").Append(SymbolDisplay.FormatLiteral(command, true));
        if (catalogCommand is null && CacheMutation(method) is { } cacheMutation)
            source.Append(", global::Respire.RespireCacheMutation.").Append(cacheMutation);
        if (catalogCommand is null) source.Append(')');
        source.Append(";\n")
            .Append("    /// <inheritdoc/>\n")
            .Append("    public ").Append(hidesObjectMember ? "new " : "")
            .Append(direct ? "" : "async ").Append(TypeName(task)).Append(' ')
            .Append(Escape(method.Name)).Append('(');
        source.Append(string.Join(", ", method.Parameters.Select(ParameterDeclaration)));
        source.Append(")\n    {\n");
        // The non-async ValueTask<RespireResult> shape reports argument and cancellation failures through the
        // returned task, matching the async shapes, instead of throwing before a task exists.
        if (cancellation is not null)
        {
            source.Append("        ");
            if (direct)
                source.Append("if (").Append(Escape(cancellation.Name)).Append(".IsCancellationRequested) return global::System.Threading.Tasks.ValueTask.FromCanceled<global::Respire.RespireResult>(")
                    .Append(Escape(cancellation.Name)).Append(");\n");
            else source.Append(Escape(cancellation.Name)).Append(".ThrowIfCancellationRequested();\n");
        }
        // Generated locals use names allocated against user parameters, including deliberately adversarial names.
        var usedNames = new HashSet<string>(method.Parameters.Select(parameter => parameter.Name), StringComparer.Ordinal);
        var values = LocalName(usedNames, "__arguments");
        var position = LocalName(usedNames, "__position");
        var element = LocalName(usedNames, "__element");
        var result = LocalName(usedNames, "__result");
        var output = LocalName(usedNames, "__output");
        var loop = LocalName(usedNames, "__index");
        var exception = LocalName(usedNames, "__exception");
        // Null expanded arrays, length overflow, and RespireValue conversions (for example a char holding an
        // isolated surrogate) can throw. Async shapes capture that in their task; the non-async shape catches it.
        var indent = direct ? "            " : "        ";
        if (direct) source.Append("        global::Respire.RespireValue[] ").Append(values).Append(";\n        try\n        {\n");
        foreach (var parameter in expanded)
        {
            source.Append(indent).Append("if (").Append(Escape(parameter.Name)).Append(" is null) throw new global::System.ArgumentNullException(nameof(")
                .Append(Escape(parameter.Name)).Append("));\n");
        }
        source.Append(indent).Append(direct ? "" : "var ").Append(values).Append(" = new global::Respire.RespireValue[checked(")
            .Append(arguments.Length - expanded.Length);
        foreach (var parameter in expanded) source.Append(" + ").Append(Escape(parameter.Name)).Append(".Length");
        source.Append(")];\n");
        if (arguments.Length != 0) source.Append(indent).Append("var ").Append(position).Append(" = 0;\n");
        foreach (var parameter in arguments)
        {
            if (expanded.Contains(parameter, SymbolEqualityComparer.Default))
                source.Append(indent).Append("foreach (var ").Append(element).Append(" in ").Append(Escape(parameter.Name)).Append(") ")
                    .Append(values).Append('[').Append(position).Append("++] = ").Append(element).Append(";\n");
            else source.Append(indent).Append(values).Append('[').Append(position).Append("++] = ").Append(Escape(parameter.Name)).Append(";\n");
        }
        if (direct)
        {
            source.Append("        }\n        catch (global::System.Exception ").Append(exception).Append(")\n        {\n")
                .Append("            return global::System.Threading.Tasks.ValueTask.FromException<global::Respire.RespireResult>(")
                .Append(exception).Append(");\n        }\n");
        }
        var call = "this." + clientField + ".ExecuteAsync(" + commandField + ", " + values + ", "
            + (flags is null ? "global::Respire.RespireCommandFlags.None" : Escape(flags.Name)) + ", "
            + (cancellation is null ? "default" : Escape(cancellation.Name)) + ")";
        if (direct) source.Append("        return ").Append(call).Append(";\n");
        else if (raw) source.Append("        return await ").Append(call).Append(".ConfigureAwait(false);\n");
        else
        {
            source.Append("        using var ").Append(result).Append(" = await ").Append(call).Append(".ConfigureAwait(false);\n");
            if (reply is not null)
            {
                if (reply is IArrayTypeSymbol array && !IsBytes(reply))
                {
                    source.Append("        if (").Append(result).Append(".IsNull) ")
                        .Append(CanBeNull(reply) ? "return " + NullLiteral(reply) + ";" : "throw new global::System.InvalidOperationException(\"The command returned null for a non-nullable result.\");").Append('\n');
                    source.Append("        ").Append(TypeName(reply)).Append(' ').Append(output).Append(" = ").Append(ArrayCreation(array.ElementType, result + ".Count")).Append(";\n")
                        .Append("        for (var ").Append(loop).Append(" = 0; ").Append(loop).Append(" < ").Append(output)
                        .Append(".Length; ").Append(loop).Append("++)\n            ").Append(output).Append('[').Append(loop).Append("] = ")
                        .Append(ReadReply(array.ElementType, result + "[" + loop + "]")).Append(";\n")
                        .Append("        return ").Append(output).Append(";\n");
                }
                else source.Append("        return ").Append(ReadReply(reply, result)).Append(";\n");
            }
        }
        source.Append("    }\n");
    }

    private static IFieldSymbol? ResolveCatalogCommand(Compilation compilation, string name)
    {
        var catalog = compilation.GetTypeByMetadataName("Respire.RespireCommands");
        if (catalog is null) return null;
        var normalizedName = NormalizeCommandName(name);
        return FindCatalogCommand(catalog, normalizedName);
    }

    private static IFieldSymbol? FindCatalogCommand(INamedTypeSymbol type, string normalizedName)
    {
        foreach (var member in type.GetMembers())
        {
            if (member is IFieldSymbol field && field.Type.ToDisplayString() == "Respire.RespireCommand"
                && NormalizeCommandName(field.Name) == normalizedName)
                return field;
            if (member is INamedTypeSymbol nested && FindCatalogCommand(nested, normalizedName) is { } found)
                return found;
        }
        return null;
    }

    private static string NormalizeCommandName(string name)
        => new(name.Where(char.IsLetterOrDigit).Select(char.ToUpperInvariant).ToArray());

    private static string ArrayCreation(ITypeSymbol element, string length)
    {
        // byte[][] needs new byte[count][], not new byte[][count].
        return element is IArrayTypeSymbol bytes
            ? "new " + TypeName(bytes.ElementType) + "[" + length + "][]"
            : "new " + TypeName(element) + "[" + length + "]";
    }

    private static string ReadReply(ITypeSymbol type, string result)
    {
        var scalar = UnwrapNullable(type);
        var conversion = IsBytes(scalar) ? result + ".AsBytes()" : scalar.SpecialType switch
        {
            SpecialType.System_String => result + ".AsString()",
            SpecialType.System_Int32 => "checked((int)" + result + ".AsInteger())",
            SpecialType.System_Int64 => result + ".AsInteger()",
            SpecialType.System_Boolean => result + ".AsBoolean()",
            SpecialType.System_Double => result + ".AsDouble()",
            _ => throw new InvalidOperationException("Unvalidated reply type."),
        };
        var absent = CanBeNull(type) ? "(" + TypeName(type) + ")" + NullLiteral(type)
            : "throw new global::System.InvalidOperationException(\"The command returned null for a non-nullable result.\")";
        return result + ".IsNull ? " + absent + " : " + conversion;
    }

    // Reference types declared in a nullable-oblivious context (#nullable disable) accept RESP nulls, as
    // hand-written oblivious code would; only a non-nullable annotation in an enabled context rejects them.
    private static bool CanBeNull(ITypeSymbol type)
        => type.NullableAnnotation == NullableAnnotation.Annotated || IsObliviousReference(type)
            || type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T };

    private static bool IsObliviousReference(ITypeSymbol type)
        => type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.None;

    // The generated file enables nullable analysis, so an oblivious reference type needs a suppressed null.
    private static string NullLiteral(ITypeSymbol type) => IsObliviousReference(type) ? "null!" : "null";

    private static string ParameterDeclaration(IParameterSymbol parameter)
    {
        var declaration = (parameter.IsParams ? "params " : "") + TypeName(parameter.Type) + " " + Escape(parameter.Name);
        if (!parameter.HasExplicitDefaultValue) return declaration;
        // Enum and primitive constants are rendered semantically, independent of source usings/aliases.
        var value = parameter.ExplicitDefaultValue;
        var literal = value switch
        {
            null => "default",
            string text => SymbolDisplay.FormatLiteral(text, true),
            char character => SymbolDisplay.FormatLiteral(character, true),
            bool flag => flag ? "true" : "false",
            float number when float.IsNaN(number) => "float.NaN",
            float number when float.IsPositiveInfinity(number) => "float.PositiveInfinity",
            float number when float.IsNegativeInfinity(number) => "float.NegativeInfinity",
            double number when double.IsNaN(number) => "double.NaN",
            double number when double.IsPositiveInfinity(number) => "double.PositiveInfinity",
            double number when double.IsNegativeInfinity(number) => "double.NegativeInfinity",
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "F",
            double number => number.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "M",
            ulong number => number.ToString(CultureInfo.InvariantCulture) + "UL",
            long number => number.ToString(CultureInfo.InvariantCulture) + "L",
            uint number => number.ToString(CultureInfo.InvariantCulture) + "U",
            _ => Convert.ToString(value, CultureInfo.InvariantCulture)!,
        };
        if (parameter.Type.TypeKind == TypeKind.Enum) literal = "(" + TypeName(parameter.Type) + ")" + literal;
        return declaration + " = " + literal;
    }

    private static string LocalName(HashSet<string> names, string candidate)
    {
        while (!names.Add(candidate)) candidate += "_";
        return candidate;
    }

    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(TypeFormat);
    private static string Escape(string name) => "@" + name;

    /// <summary>Rendered output for one interface. Value equality lets the incremental driver cache it.</summary>
    private sealed class GeneratedInterface(string? hintName, string? source, DiagnosticInfo[] diagnostics)
        : IEquatable<GeneratedInterface>
    {
        public string? HintName { get; } = hintName;
        public string? Source { get; } = source;
        public DiagnosticInfo[] Diagnostics { get; } = diagnostics;

        public static GeneratedInterface Failed(ISymbol symbol, string message)
            => new(null, null, [DiagnosticInfo.Create(symbol, message)]);

        public bool Equals(GeneratedInterface? other)
            => other is not null && HintName == other.HintName && Source == other.Source
                && Diagnostics.SequenceEqual(other.Diagnostics);

        public override bool Equals(object? obj) => Equals(obj as GeneratedInterface);

        public override int GetHashCode()
            => ((HintName is null ? 0 : StringComparer.Ordinal.GetHashCode(HintName)) * 397)
                ^ (Source is null ? 0 : StringComparer.Ordinal.GetHashCode(Source)) ^ Diagnostics.Length;
    }

    /// <summary>A diagnostic captured without Location or SyntaxTree references.</summary>
    private sealed class DiagnosticInfo(string message, string? filePath, TextSpan span, LinePositionSpan lineSpan)
        : IEquatable<DiagnosticInfo>
    {
        private readonly string _message = message;
        private readonly string? _filePath = filePath;
        private readonly TextSpan _span = span;
        private readonly LinePositionSpan _lineSpan = lineSpan;

        public static DiagnosticInfo Create(ISymbol symbol, string message)
        {
            var location = symbol.Locations.FirstOrDefault(candidate => candidate.IsInSource);
            return location?.SourceTree is { } tree
                ? new DiagnosticInfo(message, tree.FilePath, location.SourceSpan, location.GetLineSpan().Span)
                : new DiagnosticInfo(message, null, default, default);
        }

        public Diagnostic ToDiagnostic()
            => Diagnostic.Create(InvalidDeclaration,
                _filePath is null ? Location.None : Location.Create(_filePath, _span, _lineSpan), _message);

        public bool Equals(DiagnosticInfo? other)
            => other is not null && _message == other._message && _filePath == other._filePath
                && _span.Equals(other._span) && _lineSpan.Equals(other._lineSpan);

        public override bool Equals(object? obj) => Equals(obj as DiagnosticInfo);

        public override int GetHashCode() => (_message.GetHashCode() * 397) ^ _span.GetHashCode();
    }
}
