<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" Version="1.64.0" />
        <PackageReference Include="Testcontainers.Redis" Version="4.13.0" />
        <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
        <PackageReference Include="FluentAssertions" Version="8.10.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\RedisTestContainer.cs" Link="RedisTestContainer.cs" />
        <Using Include="Respire.Testing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Respire\Respire.csproj" />
    </ItemGroup>

</Project>
