<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);FENCED_LOCKS</DefineConstants>
    <DefineConstants Condition="Exists('..\..\src\Respire.Extensions.Coordination\RespireRateLimiters.cs')">$(DefineConstants);RATE_LIMITER_API</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Respire\Respire.csproj" />
    <ProjectReference Include="..\..\src\Respire.Extensions.Coordination\Respire.Extensions.Coordination.csproj" />
    <ProjectReference Include="..\..\src\Respire.Compression.Lz4\Respire.Compression.Lz4.csproj" />
    <ProjectReference Include="..\..\src\Respire.Compression.Zstd\Respire.Compression.Zstd.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Testcontainers.Redis" />
  </ItemGroup>

</Project>
