namespace Respire.Testing;

public sealed partial class RespireFakeServer
{
    // Arity includes the command name. Option syntax remains the handler's responsibility.
    private sealed record Command(int MinimumArity, int MaximumArity,
        Func<RespireFakeServer, Connection, byte[][], FakeReply> Execute);

    private static readonly Dictionary<string, Command> Commands = new(StringComparer.Ordinal)
    {
        ["XADD"] = new(5, int.MaxValue, static (server, _, args) => server.StreamAdd(args)),
        ["XGROUP"] = new(5, 6, static (server, _, args) => server.StreamCreateGroup(args)),
        ["XREAD"] = new(4, int.MaxValue, static (server, connection, args) => server.StreamRead(connection, args)),
        ["XREADGROUP"] = new(7, int.MaxValue, static (server, connection, args) => server.StreamRead(connection, args)),
        ["XACK"] = new(4, int.MaxValue, static (server, _, args) => server.StreamAcknowledge(args)),
        ["HELLO"] = new(1, int.MaxValue, static (_, connection, args) => Hello(connection, args)),
        ["PING"] = new(1, 2, static (_, connection, args) => Ping(connection, args)),
        ["SUBSCRIBE"] = new(2, int.MaxValue, static (server, connection, args) => server.Subscribe(connection, args)),
        ["UNSUBSCRIBE"] = new(1, int.MaxValue, static (server, connection, args) => server.Unsubscribe(connection, args)),
        ["PUBLISH"] = new(3, 3, static (server, _, args) => server.Publish(args)),
        ["MULTI"] = new(1, 1, static (_, connection, _) => BeginTransaction(connection)),
        ["EXEC"] = new(1, 1, static (server, connection, _) => server.ExecuteTransaction(connection)),
        ["DISCARD"] = new(1, 1, static (server, connection, _) => server.DiscardTransaction(connection)),
        ["WATCH"] = new(2, int.MaxValue, static (server, connection, args) => server.Watch(connection, args)),
        ["UNWATCH"] = new(1, 1, static (server, connection, _) => server.Unwatch(connection)),
        ["ECHO"] = new(2, 2, static (_, _, args) => FakeReply.Bulk(args[1])),
        ["SELECT"] = new(2, 2, static (_, _, args) => Token(args[1]) == "0" ? FakeReply.Ok : Syntax("SELECT")),
        ["CLIENT"] = new(2, int.MaxValue, static (_, connection, args) => Client(connection, args)),
        ["GET"] = new(2, 2, static (server, _, args) => FakeReply.Bulk(server.Find(args[1])?.Value)),
        ["SET"] = new(3, int.MaxValue, static (server, _, args) => server.Set(args)),
        ["MGET"] = new(2, int.MaxValue, static (server, _, args) => FakeReply.Array(args.Skip(1).Select(key => FakeReply.Bulk(server.Find(key)?.Data as byte[])).ToArray())),
        ["MSET"] = new(3, int.MaxValue, static (server, _, args) => server.MultiSet("MSET", args)),
        ["MSETNX"] = new(3, int.MaxValue, static (server, _, args) => server.MultiSet("MSETNX", args)),
        ["DEL"] = new(2, int.MaxValue, static (server, _, args) => FakeReply.Integer(args.Skip(1).Count(server.Remove))),
        ["UNLINK"] = new(2, int.MaxValue, static (server, _, args) => FakeReply.Integer(args.Skip(1).Count(server.Remove))),
        ["EXISTS"] = new(2, int.MaxValue, static (server, _, args) => FakeReply.Integer(args.Skip(1).Count(key => server.Find(key) is not null))),
        ["TYPE"] = new(2, 2, static (server, _, args) => FakeReply.Simple(server.Find(args[1])?.Type ?? "none")),
        ["GETDEL"] = new(2, 2, static (server, _, args) => server.GetDelete(args[1])),
        ["GETSET"] = new(3, 3, static (server, _, args) => server.GetSet(args[1], args[2])),
        ["STRLEN"] = new(2, 2, static (server, _, args) => FakeReply.Integer(server.Find(args[1])?.Value.Length ?? 0)),
        ["APPEND"] = new(3, 3, static (server, _, args) => server.Append(args[1], args[2])),
        ["INCR"] = new(2, 2, static (server, _, args) => server.Increment(args[1], 1)),
        ["INCREX"] = new(2, int.MaxValue, static (server, _, args) => server.IncrementExtended(args)),
        ["DECR"] = new(2, 2, static (server, _, args) => server.Increment(args[1], -1)),
        ["INCRBY"] = new(3, 3, static (server, _, args) => server.Increment(args[1], Integer(args[2]))),
        ["DECRBY"] = new(3, 3, static (server, _, args) => server.Increment(args[1], Integer(args[2]), subtract: true)),
        ["GETEX"] = new(2, int.MaxValue, static (server, _, args) => server.GetExpire(args)),
        ["EXPIRE"] = new(3, int.MaxValue, static (server, _, args) => server.Expire("EXPIRE", args)),
        ["PEXPIRE"] = new(3, int.MaxValue, static (server, _, args) => server.Expire("PEXPIRE", args)),
        ["EXPIREAT"] = new(3, int.MaxValue, static (server, _, args) => server.Expire("EXPIREAT", args)),
        ["PEXPIREAT"] = new(3, int.MaxValue, static (server, _, args) => server.Expire("PEXPIREAT", args)),
        ["TTL"] = new(2, 2, static (server, _, args) => server.TimeToLive("TTL", args[1])),
        ["PTTL"] = new(2, 2, static (server, _, args) => server.TimeToLive("PTTL", args[1])),
        ["EXPIRETIME"] = new(2, 2, static (server, _, args) => server.TimeToLive("EXPIRETIME", args[1])),
        ["PEXPIRETIME"] = new(2, 2, static (server, _, args) => server.TimeToLive("PEXPIRETIME", args[1])),
        ["PERSIST"] = new(2, 2, static (server, _, args) => server.Persist(args[1])),
        ["HSET"] = new(4, int.MaxValue, static (server, _, args) => server.HashSet("HSET", args)),
        ["HMSET"] = new(4, int.MaxValue, static (server, _, args) => server.HashSet("HMSET", args)),
        ["HSETNX"] = new(4, 4, static (server, _, args) => server.HashSet("HSETNX", args)),
        ["HGET"] = new(3, 3, static (server, _, args) => FakeReply.Bulk(server.Find(args[1])?.Hash.GetValueOrDefault(args[2]))),
        ["HMGET"] = new(3, int.MaxValue, static (server, _, args) => server.HashGetMany(args)),
        ["HGETALL"] = new(2, 2, static (server, connection, args) => server.HashGetAll(args[1], connection.Resp3)),
        ["HDEL"] = new(3, int.MaxValue, static (server, _, args) => server.HashDelete(args)),
        ["HEXISTS"] = new(3, 3, static (server, _, args) => FakeReply.Integer(server.Find(args[1])?.Hash.ContainsKey(args[2]) == true ? 1 : 0)),
        ["HLEN"] = new(2, 2, static (server, _, args) => FakeReply.Integer(server.Find(args[1])?.Hash.Count ?? 0)),
        ["HKEYS"] = new(2, 2, static (server, _, args) => FakeReply.Array(server.Find(args[1])?.Hash.Keys.Select(FakeReply.Bulk).ToArray() ?? [])),
        ["HVALS"] = new(2, 2, static (server, _, args) => FakeReply.Array(server.Find(args[1])?.Hash.Values.Select(FakeReply.Bulk).ToArray() ?? [])),
        ["HSTRLEN"] = new(3, 3, static (server, _, args) => FakeReply.Integer(server.Find(args[1])?.Hash.GetValueOrDefault(args[2])?.Length ?? 0)),
        ["HINCRBY"] = new(4, 4, static (server, _, args) => server.HashIncrement(args)),
        ["SADD"] = new(3, int.MaxValue, static (server, _, args) => server.SetAdd(args)),
        ["SREM"] = new(3, int.MaxValue, static (server, _, args) => server.SetRemove(args)),
        ["SMEMBERS"] = new(2, 2, static (server, _, args) => FakeReply.Set(server.Find(args[1])?.Set.Select(FakeReply.Bulk).ToArray() ?? [])),
        ["SCARD"] = new(2, 2, static (server, _, args) => FakeReply.Integer(server.Find(args[1])?.Set.Count ?? 0)),
        ["SISMEMBER"] = new(3, 3, static (server, _, args) => FakeReply.Integer(server.Find(args[1])?.Set.Contains(args[2]) == true ? 1 : 0)),
        ["SMISMEMBER"] = new(3, int.MaxValue, static (server, _, args) => server.SetContainsMany(args)),
        ["SMOVE"] = new(4, 4, static (server, _, args) => server.SetMove(args)),
        ["SINTER"] = new(2, int.MaxValue, static (server, _, args) => server.SetCombine(args, SetOperation.Intersection)),
        ["SUNION"] = new(2, int.MaxValue, static (server, _, args) => server.SetCombine(args, SetOperation.Union)),
        ["SDIFF"] = new(2, int.MaxValue, static (server, _, args) => server.SetCombine(args, SetOperation.Difference)),
        ["SINTERSTORE"] = new(3, int.MaxValue, static (server, _, args) => server.SetCombine(args, SetOperation.Intersection, store: true)),
        ["SUNIONSTORE"] = new(3, int.MaxValue, static (server, _, args) => server.SetCombine(args, SetOperation.Union, store: true)),
        ["SDIFFSTORE"] = new(3, int.MaxValue, static (server, _, args) => server.SetCombine(args, SetOperation.Difference, store: true)),
        ["SINTERCARD"] = new(3, int.MaxValue, static (server, _, args) => server.SetIntersectCount(args)),
        ["LPUSH"] = new(3, int.MaxValue, static (server, _, args) => server.ListPush(args, left: true, onlyExisting: false)),
        ["RPUSH"] = new(3, int.MaxValue, static (server, _, args) => server.ListPush(args, left: false, onlyExisting: false)),
        ["LPUSHX"] = new(3, int.MaxValue, static (server, _, args) => server.ListPush(args, left: true, onlyExisting: true)),
        ["RPUSHX"] = new(3, int.MaxValue, static (server, _, args) => server.ListPush(args, left: false, onlyExisting: true)),
        ["LPOP"] = new(2, 3, static (server, _, args) => server.ListPop(args, left: true)),
        ["RPOP"] = new(2, 3, static (server, _, args) => server.ListPop(args, left: false)),
        ["LMOVEM"] = new(5, int.MaxValue, static (server, _, args) => server.ListMoveMany(args, blocking: false)),
        ["BLMOVEM"] = new(6, int.MaxValue, static (server, _, args) => server.ListMoveMany(args, blocking: true)),
        ["LLEN"] = new(2, 2, static (server, _, args) => FakeReply.Integer(server.Find(args[1])?.List.Count ?? 0)),
        ["LRANGE"] = new(4, 4, static (server, _, args) => server.ListRange(args)),
        ["LTRIM"] = new(4, 4, static (server, _, args) => server.ListTrim(args)),
        ["LINDEX"] = new(3, 3, static (server, _, args) => server.ListIndex(args)),
        ["LSET"] = new(4, 4, static (server, _, args) => server.ListSet(args)),
        ["LREM"] = new(4, 4, static (server, _, args) => server.ListRemove(args)),
        ["LINSERT"] = new(5, 5, static (server, _, args) => server.ListInsert(args)),
        ["LPOS"] = new(3, int.MaxValue, static (server, _, args) => server.ListPosition(args)),
        ["ZADD"] = new(4, int.MaxValue, static (server, _, args) => server.SortedSetAdd(args)),
        ["ZINCRBY"] = new(4, 4, static (server, _, args) => server.SortedSetAdd(args, increment: true)),
        ["ZREM"] = new(3, int.MaxValue, static (server, _, args) => server.SortedSetRemove(args)),
        ["ZCARD"] = new(2, 2, static (server, _, args) => FakeReply.Integer(server.Find(args[1])?.SortedSet.Count ?? 0)),
        ["ZSCORE"] = new(3, 3, static (server, _, args) => server.SortedSetScores(args, many: false)),
        ["ZMSCORE"] = new(3, int.MaxValue, static (server, _, args) => server.SortedSetScores(args, many: true)),
        ["ZRANK"] = new(3, 4, static (server, _, args) => server.SortedSetRank(args, reverse: false)),
        ["ZREVRANK"] = new(3, 4, static (server, _, args) => server.SortedSetRank(args, reverse: true)),
        ["ZCOUNT"] = new(4, 4, static (server, _, args) => server.SortedSetRange(args, SortedSetRangeKind.Score, count: true)),
        ["ZLEXCOUNT"] = new(4, 4, static (server, _, args) => server.SortedSetRange(args, SortedSetRangeKind.Lex, count: true)),
        ["ZRANGE"] = new(4, int.MaxValue, static (server, connection, args) => server.SortedSetRange(args, SortedSetRangeKind.Auto, resp3: connection.Resp3)),
        ["ZREVRANGE"] = new(4, int.MaxValue, static (server, connection, args) => server.SortedSetRange(args, SortedSetRangeKind.Rank, reverse: true, resp3: connection.Resp3)),
        ["ZRANGEBYSCORE"] = new(4, int.MaxValue, static (server, connection, args) => server.SortedSetRange(args, SortedSetRangeKind.Score, resp3: connection.Resp3)),
        ["ZREVRANGEBYSCORE"] = new(4, int.MaxValue, static (server, connection, args) => server.SortedSetRange(args, SortedSetRangeKind.Score, reverse: true, resp3: connection.Resp3)),
        ["ZRANGEBYLEX"] = new(4, int.MaxValue, static (server, _, args) => server.SortedSetRange(args, SortedSetRangeKind.Lex)),
        ["ZREVRANGEBYLEX"] = new(4, int.MaxValue, static (server, _, args) => server.SortedSetRange(args, SortedSetRangeKind.Lex, reverse: true)),
        ["ZPOPMIN"] = new(2, 3, static (server, connection, args) => server.SortedSetPop(args, false, connection.Resp3)),
        ["ZPOPMAX"] = new(2, 3, static (server, connection, args) => server.SortedSetPop(args, true, connection.Resp3)),
        ["ZREMRANGEBYRANK"] = new(4, 4, static (server, _, args) => server.SortedSetRange(args, SortedSetRangeKind.Rank, remove: true)),
        ["ZREMRANGEBYSCORE"] = new(4, 4, static (server, _, args) => server.SortedSetRange(args, SortedSetRangeKind.Score, remove: true)),
        ["ZREMRANGEBYLEX"] = new(4, 4, static (server, _, args) => server.SortedSetRange(args, SortedSetRangeKind.Lex, remove: true)),
        ["ZINTERCARD"] = new(3, int.MaxValue, static (server, _, args) => server.SortedSetIntersectCount(args)),
        ["XLEN"] = new(2, 2, static (server, _, args) => FakeReply.Integer(server.Find(args[1])?.Stream.Entries.Count ?? 0)),
        ["XCFGSET"] = new(2, int.MaxValue, static (server, _, args) => server.StreamConfigure(args)),
    };
}
