<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks />
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../samples/Respire.Samples.Aspire.AppHost/Respire.Samples.Aspire.AppHost.csproj" />
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" />
  </ItemGroup>
</Project>
