<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Respire\Respire.csproj" />
        <ProjectReference Include="..\..\src\Respire.Compression.Lz4\Respire.Compression.Lz4.csproj" />
        <ProjectReference Include="..\..\src\Respire.Compression.Zstd\Respire.Compression.Zstd.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="Microsoft.Testing.Extensions.HangDump" />
    </ItemGroup>

</Project>
