// <auto-generated />
// Run tools/Generate-StackExchangeCompat.ps1 after updating StackExchange.Redis.
#nullable disable
namespace Respire.StackExchangeCompat;
partial class CompatDatabase
{
    /// <inheritdoc />
    public global::System.Boolean ArrayDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @index, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayDelete");
    /// <inheritdoc />
    public global::System.Boolean ArraySeek(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @index, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArraySeek");
    /// <inheritdoc />
    public global::System.Boolean ArraySet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @index, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArraySet");
    /// <inheritdoc />
    public global::System.Boolean GeoAdd(global::StackExchange.Redis.RedisKey @key, global::System.Double @longitude, global::System.Double @latitude, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoAdd");
    /// <inheritdoc />
    public global::System.Boolean GeoAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.GeoEntry @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoAdd");
    /// <inheritdoc />
    public global::System.Boolean GeoRemove(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoRemove");
    /// <inheritdoc />
    public global::System.Boolean HashExists(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashExists");
    /// <inheritdoc />
    public global::System.Boolean HyperLogLogAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HyperLogLogAdd");
    /// <inheritdoc />
    public global::System.Boolean HyperLogLogAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HyperLogLogAdd");
    /// <inheritdoc />
    public global::System.Boolean KeyCopy(global::StackExchange.Redis.RedisKey @sourceKey, global::StackExchange.Redis.RedisKey @destinationKey, global::System.Int32 @destinationDatabase, global::System.Boolean @replace, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyCopy");
    /// <inheritdoc />
    public global::System.Boolean KeyMove(global::StackExchange.Redis.RedisKey @key, global::System.Int32 @database, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyMove");
    /// <inheritdoc />
    public global::System.Boolean KeyRename(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisKey @newKey, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyRename");
    /// <inheritdoc />
    public global::System.Boolean KeyTouch(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyTouch");
    /// <inheritdoc />
    public global::System.Boolean SetContains(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetContains");
    /// <inheritdoc />
    public global::System.Boolean SetMove(global::StackExchange.Redis.RedisKey @source, global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetMove");
    /// <inheritdoc />
    public global::System.Boolean SortedSetUpdate(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::System.Double @score, global::StackExchange.Redis.SortedSetWhen @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetUpdate");
    /// <inheritdoc />
    public global::System.Boolean StreamConsumerGroupSetPosition(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @position, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamConsumerGroupSetPosition");
    /// <inheritdoc />
    public global::System.Boolean StreamCreateConsumerGroup(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::System.Nullable<global::StackExchange.Redis.RedisValue> @position, global::System.Boolean @createStream, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamCreateConsumerGroup");
    /// <inheritdoc />
    public global::System.Boolean StreamCreateConsumerGroup(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::System.Nullable<global::StackExchange.Redis.RedisValue> @position, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamCreateConsumerGroup");
    /// <inheritdoc />
    public global::System.Boolean StreamDeleteConsumerGroup(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamDeleteConsumerGroup");
    /// <inheritdoc />
    public global::System.Boolean StringDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.ValueCondition @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringDelete");
    /// <inheritdoc />
    public global::System.Boolean StringGetBit(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @offset, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringGetBit");
    /// <inheritdoc />
    public global::System.Boolean StringSet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.Expiration @expiry, global::StackExchange.Redis.ValueCondition @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringSet");
    /// <inheritdoc />
    public global::System.Boolean StringSet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::System.Nullable<global::System.TimeSpan> @expiry, global::System.Boolean @keepTtl, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringSet");
    /// <inheritdoc />
    public global::System.Boolean StringSet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::System.Nullable<global::System.TimeSpan> @expiry, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringSet");
    /// <inheritdoc />
    public global::System.Boolean StringSet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::System.Nullable<global::System.TimeSpan> @expiry, global::StackExchange.Redis.When @when)
        => throw Compatibility.Unsupported("StringSet");
    /// <inheritdoc />
    public global::System.Boolean StringSet(global::System.Collections.Generic.KeyValuePair<global::StackExchange.Redis.RedisKey, global::StackExchange.Redis.RedisValue>[] @values, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringSet");
    /// <inheritdoc />
    public global::System.Boolean StringSet(global::System.Collections.Generic.KeyValuePair<global::StackExchange.Redis.RedisKey, global::StackExchange.Redis.RedisValue>[] @values, global::StackExchange.Redis.When @when, global::StackExchange.Redis.Expiration @expiry, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringSet");
    /// <inheritdoc />
    public global::System.Boolean StringSetBit(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @offset, global::System.Boolean @bit, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringSetBit");
    /// <inheritdoc />
    public global::System.Boolean VectorSetAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.VectorSetAddRequest @request, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetAdd");
    /// <inheritdoc />
    public global::System.Boolean VectorSetContains(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetContains");
    /// <inheritdoc />
    public global::System.Boolean VectorSetRemove(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetRemove");
    /// <inheritdoc />
    public global::System.Boolean VectorSetSetAttributesJson(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::System.String @attributesJson, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetSetAttributesJson");
    /// <inheritdoc />
    public global::System.Boolean[] SetContains(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetContains");
    /// <inheritdoc />
    public global::System.Byte[] KeyDump(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyDump");
    /// <inheritdoc />
    public global::System.Double HashDecrement(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::System.Double @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashDecrement");
    /// <inheritdoc />
    public global::System.Double HashIncrement(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::System.Double @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashIncrement");
    /// <inheritdoc />
    public global::System.Double SortedSetDecrement(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::System.Double @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetDecrement");
    /// <inheritdoc />
    public global::System.Double SortedSetIncrement(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::System.Double @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetIncrement");
    /// <inheritdoc />
    public global::System.Double StringDecrement(global::StackExchange.Redis.RedisKey @key, global::System.Double @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringDecrement");
    /// <inheritdoc />
    public global::System.Double StringIncrement(global::StackExchange.Redis.RedisKey @key, global::System.Double @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringIncrement");
    /// <inheritdoc />
    public global::System.Int32 ArrayDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex[] @indices, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayDelete");
    /// <inheritdoc />
    public global::System.Int32 ArraySet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayEntry[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArraySet");
    /// <inheritdoc />
    public global::System.Int32 ArraySet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @index, global::StackExchange.Redis.RedisValue[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArraySet");
    /// <inheritdoc />
    public global::System.Int32 VectorSetDimension(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetDimension");
    /// <inheritdoc />
    public global::System.Int64 GeoAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.GeoEntry[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoAdd");
    /// <inheritdoc />
    public global::System.Int64 GeoSearchAndStore(global::StackExchange.Redis.RedisKey @sourceKey, global::StackExchange.Redis.RedisKey @destinationKey, global::System.Double @longitude, global::System.Double @latitude, global::StackExchange.Redis.GeoSearchShape @shape, global::System.Int32 @count, global::System.Boolean @demandClosest, global::System.Nullable<global::StackExchange.Redis.Order> @order, global::System.Boolean @storeDistances, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoSearchAndStore");
    /// <inheritdoc />
    public global::System.Int64 GeoSearchAndStore(global::StackExchange.Redis.RedisKey @sourceKey, global::StackExchange.Redis.RedisKey @destinationKey, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.GeoSearchShape @shape, global::System.Int32 @count, global::System.Boolean @demandClosest, global::System.Nullable<global::StackExchange.Redis.Order> @order, global::System.Boolean @storeDistances, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoSearchAndStore");
    /// <inheritdoc />
    public global::System.Int64 HashDecrement(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::System.Int64 @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashDecrement");
    /// <inheritdoc />
    public global::System.Int64 HashIncrement(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::System.Int64 @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashIncrement");
    /// <inheritdoc />
    public global::System.Int64 HashStringLength(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashStringLength");
    /// <inheritdoc />
    public global::System.Int64 HyperLogLogLength(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HyperLogLogLength");
    /// <inheritdoc />
    public global::System.Int64 HyperLogLogLength(global::StackExchange.Redis.RedisKey[] @keys, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HyperLogLogLength");
    /// <inheritdoc />
    public global::System.Int64 KeyTouch(global::StackExchange.Redis.RedisKey[] @keys, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyTouch");
    /// <inheritdoc />
    public global::System.Int64 ListInsertAfter(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @pivot, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListInsertAfter");
    /// <inheritdoc />
    public global::System.Int64 ListInsertBefore(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @pivot, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListInsertBefore");
    /// <inheritdoc />
    public global::System.Int64 ListPosition(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @element, global::System.Int64 @rank, global::System.Int64 @maxLength, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListPosition");
    /// <inheritdoc />
    public global::System.Int64 SetCombineAndStore(global::StackExchange.Redis.SetOperation @operation, global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisKey @first, global::StackExchange.Redis.RedisKey @second, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetCombineAndStore");
    /// <inheritdoc />
    public global::System.Int64 SetCombineAndStore(global::StackExchange.Redis.SetOperation @operation, global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisKey[] @keys, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetCombineAndStore");
    /// <inheritdoc />
    public global::System.Int64 SetCombineLength(global::StackExchange.Redis.SetOperation @operation, global::StackExchange.Redis.RedisKey[] @keys, global::System.Int64 @limit, global::System.Boolean @approximate, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetCombineLength");
    /// <inheritdoc />
    public global::System.Int64 SetIntersectionLength(global::StackExchange.Redis.RedisKey[] @keys, global::System.Int64 @limit, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetIntersectionLength");
    /// <inheritdoc />
    public global::System.Int64 SortAndStore(global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisKey @key, global::System.Int64 @skip, global::System.Int64 @take, global::StackExchange.Redis.Order @order, global::StackExchange.Redis.SortType @sortType, global::StackExchange.Redis.RedisValue @by, global::StackExchange.Redis.RedisValue[] @get, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortAndStore");
    /// <inheritdoc />
    public global::System.Int64 SortedSetCombineAndStore(global::StackExchange.Redis.SetOperation @operation, global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisKey @first, global::StackExchange.Redis.RedisKey @second, global::StackExchange.Redis.Aggregate @aggregate, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetCombineAndStore");
    /// <inheritdoc />
    public global::System.Int64 SortedSetCombineAndStore(global::StackExchange.Redis.SetOperation @operation, global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisKey[] @keys, global::System.Double[] @weights, global::StackExchange.Redis.Aggregate @aggregate, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetCombineAndStore");
    /// <inheritdoc />
    public global::System.Int64 SortedSetIntersectionLength(global::StackExchange.Redis.RedisKey[] @keys, global::System.Int64 @limit, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetIntersectionLength");
    /// <inheritdoc />
    public global::System.Int64 SortedSetLengthByValue(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @min, global::StackExchange.Redis.RedisValue @max, global::StackExchange.Redis.Exclude @exclude, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetLengthByValue");
    /// <inheritdoc />
    public global::System.Int64 SortedSetRangeAndStore(global::StackExchange.Redis.RedisKey @sourceKey, global::StackExchange.Redis.RedisKey @destinationKey, global::StackExchange.Redis.RedisValue @start, global::StackExchange.Redis.RedisValue @stop, global::StackExchange.Redis.SortedSetOrder @sortedSetOrder, global::StackExchange.Redis.Exclude @exclude, global::StackExchange.Redis.Order @order, global::System.Int64 @skip, global::System.Nullable<global::System.Int64> @take, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRangeAndStore");
    /// <inheritdoc />
    public global::System.Int64 SortedSetRemoveRangeByRank(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @start, global::System.Int64 @stop, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRemoveRangeByRank");
    /// <inheritdoc />
    public global::System.Int64 SortedSetRemoveRangeByScore(global::StackExchange.Redis.RedisKey @key, global::System.Double @start, global::System.Double @stop, global::StackExchange.Redis.Exclude @exclude, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRemoveRangeByScore");
    /// <inheritdoc />
    public global::System.Int64 SortedSetRemoveRangeByValue(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @min, global::StackExchange.Redis.RedisValue @max, global::StackExchange.Redis.Exclude @exclude, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRemoveRangeByValue");
    /// <inheritdoc />
    public global::System.Int64 SortedSetUpdate(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.SortedSetEntry[] @values, global::StackExchange.Redis.SortedSetWhen @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetUpdate");
    /// <inheritdoc />
    public global::System.Int64 StreamAcknowledge(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @messageId, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAcknowledge");
    /// <inheritdoc />
    public global::System.Int64 StreamAcknowledge(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue[] @messageIds, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAcknowledge");
    /// <inheritdoc />
    public global::System.Int64 StreamDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @messageIds, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamDelete");
    /// <inheritdoc />
    public global::System.Int64 StreamDeleteConsumer(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @consumerName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamDeleteConsumer");
    /// <inheritdoc />
    public global::System.Int64 StreamLength(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamLength");
    /// <inheritdoc />
    public global::System.Int64 StreamNegativeAcknowledge(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.StreamNackMode @mode, global::StackExchange.Redis.RedisValue @messageId, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamNegativeAcknowledge");
    /// <inheritdoc />
    public global::System.Int64 StreamNegativeAcknowledge(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.StreamNackMode @mode, global::StackExchange.Redis.RedisValue[] @messageIds, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamNegativeAcknowledge");
    /// <inheritdoc />
    public global::System.Int64 StreamTrim(global::StackExchange.Redis.RedisKey @key, global::System.Int32 @maxLength, global::System.Boolean @useApproximateMaxLength, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamTrim");
    /// <inheritdoc />
    public global::System.Int64 StreamTrim(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @maxLength, global::System.Boolean @useApproximateMaxLength, global::System.Nullable<global::System.Int64> @limit, global::StackExchange.Redis.StreamTrimMode @mode, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamTrim");
    /// <inheritdoc />
    public global::System.Int64 StreamTrimByMinId(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @minId, global::System.Boolean @useApproximateMaxLength, global::System.Nullable<global::System.Int64> @limit, global::StackExchange.Redis.StreamTrimMode @mode, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamTrimByMinId");
    /// <inheritdoc />
    public global::System.Int64 StringAppend(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringAppend");
    /// <inheritdoc />
    public global::System.Int64 StringBitCount(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @start, global::System.Int64 @end, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringBitCount");
    /// <inheritdoc />
    public global::System.Int64 StringBitCount(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @start, global::System.Int64 @end, global::StackExchange.Redis.StringIndexType @indexType, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringBitCount");
    /// <inheritdoc />
    public global::System.Int64 StringBitOperation(global::StackExchange.Redis.Bitwise @operation, global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisKey @first, global::StackExchange.Redis.RedisKey @second, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringBitOperation");
    /// <inheritdoc />
    public global::System.Int64 StringBitOperation(global::StackExchange.Redis.Bitwise @operation, global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisKey[] @keys, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringBitOperation");
    /// <inheritdoc />
    public global::System.Int64 StringBitPosition(global::StackExchange.Redis.RedisKey @key, global::System.Boolean @bit, global::System.Int64 @start, global::System.Int64 @end, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringBitPosition");
    /// <inheritdoc />
    public global::System.Int64 StringBitPosition(global::StackExchange.Redis.RedisKey @key, global::System.Boolean @bit, global::System.Int64 @start, global::System.Int64 @end, global::StackExchange.Redis.StringIndexType @indexType, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringBitPosition");
    /// <inheritdoc />
    public global::System.Int64 StringLength(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringLength");
    /// <inheritdoc />
    public global::System.Int64 StringLongestCommonSubsequenceLength(global::StackExchange.Redis.RedisKey @first, global::StackExchange.Redis.RedisKey @second, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringLongestCommonSubsequenceLength");
    /// <inheritdoc />
    public global::System.Int64 VectorSetLength(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetLength");
    /// <inheritdoc />
    public global::System.Int64[] HashFieldGetExpireDateTime(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @hashFields, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetExpireDateTime");
    /// <inheritdoc />
    public global::System.Int64[] HashFieldGetTimeToLive(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @hashFields, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetTimeToLive");
    /// <inheritdoc />
    public global::System.Int64[] ListPositions(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @element, global::System.Int64 @count, global::System.Int64 @rank, global::System.Int64 @maxLength, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListPositions");
    /// <inheritdoc />
    public global::StackExchange.Redis.ArrayInfo ArrayInfo(global::StackExchange.Redis.RedisKey @key, global::System.Boolean @full, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayInfo");
    /// <inheritdoc />
    public global::StackExchange.Redis.ExpireResult[] HashFieldExpire(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @hashFields, global::System.DateTime @expiry, global::StackExchange.Redis.ExpireWhen @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldExpire");
    /// <inheritdoc />
    public global::StackExchange.Redis.ExpireResult[] HashFieldExpire(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @hashFields, global::System.TimeSpan @expiry, global::StackExchange.Redis.ExpireWhen @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldExpire");
    /// <inheritdoc />
    public global::StackExchange.Redis.GeoRadiusResult[] GeoRadius(global::StackExchange.Redis.RedisKey @key, global::System.Double @longitude, global::System.Double @latitude, global::System.Double @radius, global::StackExchange.Redis.GeoUnit @unit, global::System.Int32 @count, global::System.Nullable<global::StackExchange.Redis.Order> @order, global::StackExchange.Redis.GeoRadiusOptions @options, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoRadius");
    /// <inheritdoc />
    public global::StackExchange.Redis.GeoRadiusResult[] GeoRadius(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::System.Double @radius, global::StackExchange.Redis.GeoUnit @unit, global::System.Int32 @count, global::System.Nullable<global::StackExchange.Redis.Order> @order, global::StackExchange.Redis.GeoRadiusOptions @options, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoRadius");
    /// <inheritdoc />
    public global::StackExchange.Redis.GeoRadiusResult[] GeoSearch(global::StackExchange.Redis.RedisKey @key, global::System.Double @longitude, global::System.Double @latitude, global::StackExchange.Redis.GeoSearchShape @shape, global::System.Int32 @count, global::System.Boolean @demandClosest, global::System.Nullable<global::StackExchange.Redis.Order> @order, global::StackExchange.Redis.GeoRadiusOptions @options, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoSearch");
    /// <inheritdoc />
    public global::StackExchange.Redis.GeoRadiusResult[] GeoSearch(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.GeoSearchShape @shape, global::System.Int32 @count, global::System.Boolean @demandClosest, global::System.Nullable<global::StackExchange.Redis.Order> @order, global::StackExchange.Redis.GeoRadiusOptions @options, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoSearch");
    /// <inheritdoc />
    public global::StackExchange.Redis.HashEntry[] HashRandomFieldsWithValues(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashRandomFieldsWithValues");
    /// <inheritdoc />
    public new global::StackExchange.Redis.ITransaction CreateTransaction(global::System.Object @asyncState)
        => throw Compatibility.Unsupported("CreateTransaction");
    /// <inheritdoc />
    public global::StackExchange.Redis.LCSMatchResult StringLongestCommonSubsequenceWithMatches(global::StackExchange.Redis.RedisKey @first, global::StackExchange.Redis.RedisKey @second, global::System.Int64 @minLength, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringLongestCommonSubsequenceWithMatches");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::StackExchange.Redis.RedisValue> VectorSetGetLinks(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetGetLinks");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::StackExchange.Redis.RedisValue> VectorSetRange(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @start, global::StackExchange.Redis.RedisValue @end, global::System.Int64 @count, global::StackExchange.Redis.Exclude @exclude, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetRange");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::StackExchange.Redis.VectorSetLink> VectorSetGetLinksWithScores(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetGetLinksWithScores");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::StackExchange.Redis.VectorSetSimilaritySearchResult> VectorSetSimilaritySearch(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.VectorSetSimilaritySearchRequest @query, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetSimilaritySearch");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::System.Byte> HashFieldGetLeaseAndDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetLeaseAndDelete");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::System.Byte> HashFieldGetLeaseAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::System.DateTime @expiry, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetLeaseAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::System.Byte> HashFieldGetLeaseAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::System.Nullable<global::System.TimeSpan> @expiry, global::System.Boolean @persist, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetLeaseAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::System.Byte> StringGetLease(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringGetLease");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::System.Nullable<global::System.Int64>> StringBitField(global::StackExchange.Redis.RedisKey @key, global::System.ReadOnlyMemory<global::StackExchange.Redis.BitFieldOperation> @operations, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringBitField");
    /// <inheritdoc />
    public global::StackExchange.Redis.Lease<global::System.Single> VectorSetGetApproximateVector(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetGetApproximateVector");
    /// <inheritdoc />
    public global::StackExchange.Redis.ListPopResult ListLeftPop(global::StackExchange.Redis.RedisKey[] @keys, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListLeftPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.ListPopResult ListRightPop(global::StackExchange.Redis.RedisKey[] @keys, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListRightPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.PersistResult[] HashFieldPersist(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @hashFields, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldPersist");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayEntry[] ArrayGrep(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.ArrayGrepRequest @request, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayGrep");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayEntry[] ArrayScan(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @start, global::StackExchange.Redis.RedisArrayIndex @end, global::System.Int32 @limit, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayScan");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayIndex ArrayCount(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayCount");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayIndex ArrayDeleteRange(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @start, global::StackExchange.Redis.RedisArrayIndex @end, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayDeleteRange");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayIndex ArrayDeleteRange(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayRange[] @ranges, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayDeleteRange");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayIndex ArrayInsert(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayInsert");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayIndex ArrayInsert(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayInsert");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayIndex ArrayLength(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayLength");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayIndex ArrayRing(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @maxLength, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayRing");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisArrayIndex ArrayRing(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @maxLength, global::StackExchange.Redis.RedisValue[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayRing");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisKey KeyRandom(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyRandom");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult Execute(global::System.String @command, global::System.Collections.Generic.ICollection<global::System.Object> @args, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Execute");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult Execute(global::System.String @command, global::System.Object[] @args)
        => throw Compatibility.Unsupported("Execute");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult ScriptEvaluate(global::System.Byte[] @hash, global::StackExchange.Redis.RedisKey[] @keys, global::StackExchange.Redis.RedisValue[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptEvaluate");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult ScriptEvaluate(global::StackExchange.Redis.LoadedLuaScript @script, global::System.Object @parameters, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptEvaluate");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult ScriptEvaluate(global::StackExchange.Redis.LuaScript @script, global::System.Object @parameters, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptEvaluate");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult ScriptEvaluate(global::System.String @script, global::StackExchange.Redis.RedisKey[] @keys, global::StackExchange.Redis.RedisValue[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptEvaluate");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult ScriptEvaluateReadOnly(global::System.Byte[] @hash, global::StackExchange.Redis.RedisKey[] @keys, global::StackExchange.Redis.RedisValue[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptEvaluateReadOnly");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult ScriptEvaluateReadOnly(global::System.String @script, global::StackExchange.Redis.RedisKey[] @keys, global::StackExchange.Redis.RedisValue[] @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptEvaluateReadOnly");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisStream[] StreamRead(global::StackExchange.Redis.StreamPosition[] @streamPositions, global::System.Nullable<global::System.Int32> @countPerStream, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamRead");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisStream[] StreamRead(global::StackExchange.Redis.StreamPosition[] @streamPositions, global::System.Nullable<global::System.Int32> @countPerStream, global::System.Nullable<global::System.Int32> @maxCount, global::System.Nullable<global::System.Int32> @maxSize, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamRead");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisStream[] StreamReadGroup(global::StackExchange.Redis.StreamPosition[] @streamPositions, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @consumerName, global::System.Nullable<global::System.Int32> @countPerStream, global::System.Boolean @noAck, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamReadGroup");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisStream[] StreamReadGroup(global::StackExchange.Redis.StreamPosition[] @streamPositions, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @consumerName, global::System.Nullable<global::System.Int32> @countPerStream, global::System.Boolean @noAck, global::System.Nullable<global::System.TimeSpan> @claimMinIdleTime, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamReadGroup");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisStream[] StreamReadGroup(global::StackExchange.Redis.StreamPosition[] @streamPositions, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @consumerName, global::System.Nullable<global::System.Int32> @countPerStream, global::System.Boolean @noAck, global::System.Nullable<global::System.TimeSpan> @claimMinIdleTime, global::System.Nullable<global::System.Int32> @maxCount, global::System.Nullable<global::System.Int32> @maxSize, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamReadGroup");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisStream[] StreamReadGroup(global::StackExchange.Redis.StreamPosition[] @streamPositions, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @consumerName, global::System.Nullable<global::System.Int32> @countPerStream, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamReadGroup");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisType KeyType(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyType");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue ArrayGet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @index, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayGet");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue ArrayOperation(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @start, global::StackExchange.Redis.RedisArrayIndex @end, global::StackExchange.Redis.ArrayOperation @operation, global::StackExchange.Redis.RedisValue @operand, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayOperation");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue DebugObject(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("DebugObject");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue HashFieldGetAndDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetAndDelete");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue HashFieldGetAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::System.DateTime @expiry, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue HashFieldGetAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @hashField, global::System.Nullable<global::System.TimeSpan> @expiry, global::System.Boolean @persist, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue HashFieldSetAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.HashEntry[] @hashFields, global::System.DateTime @expiry, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldSetAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue HashFieldSetAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.HashEntry[] @hashFields, global::System.Nullable<global::System.TimeSpan> @expiry, global::System.Boolean @keepTtl, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldSetAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue HashFieldSetAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @field, global::StackExchange.Redis.RedisValue @value, global::System.DateTime @expiry, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldSetAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue HashFieldSetAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @field, global::StackExchange.Redis.RedisValue @value, global::System.Nullable<global::System.TimeSpan> @expiry, global::System.Boolean @keepTtl, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldSetAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue HashRandomField(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashRandomField");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue ListLeftPop(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListLeftPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue ListMove(global::StackExchange.Redis.RedisKey @sourceKey, global::StackExchange.Redis.RedisKey @destinationKey, global::StackExchange.Redis.ListSide @sourceSide, global::StackExchange.Redis.ListSide @destinationSide, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListMove");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue ListRightPop(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListRightPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue LockQuery(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LockQuery");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue SetPop(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue SetRandomMember(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetRandomMember");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue SortedSetRandomMember(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRandomMember");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StreamAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.NameValueEntry[] @streamPairs, global::StackExchange.Redis.StreamAddOptions @options, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAdd");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StreamAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.NameValueEntry[] @streamPairs, global::StackExchange.Redis.StreamIdempotentId @idempotentId, global::System.Nullable<global::System.Int64> @maxLength, global::System.Boolean @useApproximateMaxLength, global::System.Nullable<global::System.Int64> @limit, global::StackExchange.Redis.StreamTrimMode @trimMode, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAdd");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StreamAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.NameValueEntry[] @streamPairs, global::System.Nullable<global::StackExchange.Redis.RedisValue> @messageId, global::System.Nullable<global::System.Int32> @maxLength, global::System.Boolean @useApproximateMaxLength, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAdd");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StreamAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.NameValueEntry[] @streamPairs, global::System.Nullable<global::StackExchange.Redis.RedisValue> @messageId, global::System.Nullable<global::System.Int64> @maxLength, global::System.Boolean @useApproximateMaxLength, global::System.Nullable<global::System.Int64> @limit, global::StackExchange.Redis.StreamTrimMode @trimMode, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAdd");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StreamAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @streamField, global::StackExchange.Redis.RedisValue @streamValue, global::StackExchange.Redis.StreamAddOptions @options, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAdd");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StreamAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @streamField, global::StackExchange.Redis.RedisValue @streamValue, global::StackExchange.Redis.StreamIdempotentId @idempotentId, global::System.Nullable<global::System.Int64> @maxLength, global::System.Boolean @useApproximateMaxLength, global::System.Nullable<global::System.Int64> @limit, global::StackExchange.Redis.StreamTrimMode @trimMode, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAdd");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StreamAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @streamField, global::StackExchange.Redis.RedisValue @streamValue, global::System.Nullable<global::StackExchange.Redis.RedisValue> @messageId, global::System.Nullable<global::System.Int32> @maxLength, global::System.Boolean @useApproximateMaxLength, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAdd");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StreamAdd(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @streamField, global::StackExchange.Redis.RedisValue @streamValue, global::System.Nullable<global::StackExchange.Redis.RedisValue> @messageId, global::System.Nullable<global::System.Int64> @maxLength, global::System.Boolean @useApproximateMaxLength, global::System.Nullable<global::System.Int64> @limit, global::StackExchange.Redis.StreamTrimMode @trimMode, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAdd");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StringGetDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringGetDelete");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StringGetRange(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @start, global::System.Int64 @end, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringGetRange");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StringGetSet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringGetSet");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StringGetSetExpiry(global::StackExchange.Redis.RedisKey @key, global::System.DateTime @expiry, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringGetSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StringGetSetExpiry(global::StackExchange.Redis.RedisKey @key, global::System.Nullable<global::System.TimeSpan> @expiry, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringGetSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StringSetAndGet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::System.Nullable<global::System.TimeSpan> @expiry, global::System.Boolean @keepTtl, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringSetAndGet");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StringSetAndGet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @value, global::System.Nullable<global::System.TimeSpan> @expiry, global::StackExchange.Redis.When @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringSetAndGet");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue StringSetRange(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @offset, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringSetRange");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue VectorSetRandomMember(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetRandomMember");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] ArrayGet(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex[] @indices, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayGet");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] ArrayGetRange(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisArrayIndex @start, global::StackExchange.Redis.RedisArrayIndex @end, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayGetRange");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] ArrayLastItems(global::StackExchange.Redis.RedisKey @key, global::System.Int32 @count, global::System.Boolean @reverse, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayLastItems");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] HashFieldGetAndDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @hashFields, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetAndDelete");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] HashFieldGetAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @hashFields, global::System.DateTime @expiry, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] HashFieldGetAndSetExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @hashFields, global::System.Nullable<global::System.TimeSpan> @expiry, global::System.Boolean @persist, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashFieldGetAndSetExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] HashKeys(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashKeys");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] HashRandomFields(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashRandomFields");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] HashValues(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashValues");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] ListLeftPop(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListLeftPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] ListMove(global::StackExchange.Redis.RedisKey @sourceKey, global::StackExchange.Redis.RedisKey @destinationKey, global::StackExchange.Redis.ListSide @sourceSide, global::StackExchange.Redis.ListSide @destinationSide, global::System.Int64 @count, global::StackExchange.Redis.ListMoveCount @mode, global::StackExchange.Redis.ListMoveOrder @order, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListMove");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] ListRightPop(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListRightPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] SetCombine(global::StackExchange.Redis.SetOperation @operation, global::StackExchange.Redis.RedisKey @first, global::StackExchange.Redis.RedisKey @second, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetCombine");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] SetCombine(global::StackExchange.Redis.SetOperation @operation, global::StackExchange.Redis.RedisKey[] @keys, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetCombine");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] SetPop(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] SetRandomMembers(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetRandomMembers");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] Sort(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @skip, global::System.Int64 @take, global::StackExchange.Redis.Order @order, global::StackExchange.Redis.SortType @sortType, global::StackExchange.Redis.RedisValue @by, global::StackExchange.Redis.RedisValue[] @get, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Sort");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] SortedSetCombine(global::StackExchange.Redis.SetOperation @operation, global::StackExchange.Redis.RedisKey[] @keys, global::System.Double[] @weights, global::StackExchange.Redis.Aggregate @aggregate, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetCombine");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] SortedSetRandomMembers(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRandomMembers");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] SortedSetRangeByValue(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @min, global::StackExchange.Redis.RedisValue @max, global::StackExchange.Redis.Exclude @exclude, global::System.Int64 @skip, global::System.Int64 @take, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRangeByValue");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] SortedSetRangeByValue(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @min, global::StackExchange.Redis.RedisValue @max, global::StackExchange.Redis.Exclude @exclude, global::StackExchange.Redis.Order @order, global::System.Int64 @skip, global::System.Int64 @take, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRangeByValue");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] StreamClaimIdsOnly(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @consumerGroup, global::StackExchange.Redis.RedisValue @claimingConsumer, global::System.Int64 @minIdleTimeInMs, global::StackExchange.Redis.RedisValue[] @messageIds, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamClaimIdsOnly");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue[] VectorSetRandomMembers(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetRandomMembers");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValueWithExpiry StringGetWithExpiry(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringGetWithExpiry");
    /// <inheritdoc />
    public global::StackExchange.Redis.RespResult ExecuteResp(global::System.String @command, global::System.ReadOnlyMemory<global::StackExchange.Redis.RedisKeyOrValue> @args, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ExecuteResp");
    /// <inheritdoc />
    public global::StackExchange.Redis.RespResult ScriptEvaluateReadOnlyResp(global::System.String @script, global::System.ReadOnlyMemory<global::StackExchange.Redis.RedisKey> @keys, global::System.ReadOnlyMemory<global::StackExchange.Redis.RedisValue> @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptEvaluateReadOnlyResp");
    /// <inheritdoc />
    public global::StackExchange.Redis.RespResult ScriptEvaluateResp(global::System.String @script, global::System.ReadOnlyMemory<global::StackExchange.Redis.RedisKey> @keys, global::System.ReadOnlyMemory<global::StackExchange.Redis.RedisValue> @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptEvaluateResp");
    /// <inheritdoc />
    public global::StackExchange.Redis.SortedSetEntry[] SortedSetCombineWithScores(global::StackExchange.Redis.SetOperation @operation, global::StackExchange.Redis.RedisKey[] @keys, global::System.Double[] @weights, global::StackExchange.Redis.Aggregate @aggregate, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetCombineWithScores");
    /// <inheritdoc />
    public global::StackExchange.Redis.SortedSetEntry[] SortedSetPop(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.Order @order, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.SortedSetEntry[] SortedSetRandomMembersWithScores(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRandomMembersWithScores");
    /// <inheritdoc />
    public global::StackExchange.Redis.SortedSetPopResult SortedSetPop(global::StackExchange.Redis.RedisKey[] @keys, global::System.Int64 @count, global::StackExchange.Redis.Order @order, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetPop");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamAutoClaimIdsOnlyResult StreamAutoClaimIdsOnly(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @consumerGroup, global::StackExchange.Redis.RedisValue @claimingConsumer, global::System.Int64 @minIdleTimeInMs, global::StackExchange.Redis.RedisValue @startAtId, global::System.Nullable<global::System.Int32> @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAutoClaimIdsOnly");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamAutoClaimResult StreamAutoClaim(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @consumerGroup, global::StackExchange.Redis.RedisValue @claimingConsumer, global::System.Int64 @minIdleTimeInMs, global::StackExchange.Redis.RedisValue @startAtId, global::System.Nullable<global::System.Int32> @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAutoClaim");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamConsumerInfo[] StreamConsumerInfo(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamConsumerInfo");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamEntry[] StreamClaim(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @consumerGroup, global::StackExchange.Redis.RedisValue @claimingConsumer, global::System.Int64 @minIdleTimeInMs, global::StackExchange.Redis.RedisValue[] @messageIds, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamClaim");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamEntry[] StreamRange(global::StackExchange.Redis.RedisKey @key, global::System.Nullable<global::StackExchange.Redis.RedisValue> @minId, global::System.Nullable<global::StackExchange.Redis.RedisValue> @maxId, global::System.Nullable<global::System.Int32> @count, global::StackExchange.Redis.Order @messageOrder, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamRange");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamEntry[] StreamRead(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @position, global::System.Nullable<global::System.Int32> @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamRead");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamEntry[] StreamReadGroup(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @consumerName, global::System.Nullable<global::StackExchange.Redis.RedisValue> @position, global::System.Nullable<global::System.Int32> @count, global::System.Boolean @noAck, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamReadGroup");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamEntry[] StreamReadGroup(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @consumerName, global::System.Nullable<global::StackExchange.Redis.RedisValue> @position, global::System.Nullable<global::System.Int32> @count, global::System.Boolean @noAck, global::System.Nullable<global::System.TimeSpan> @claimMinIdleTime, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamReadGroup");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamEntry[] StreamReadGroup(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.RedisValue @consumerName, global::System.Nullable<global::StackExchange.Redis.RedisValue> @position, global::System.Nullable<global::System.Int32> @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamReadGroup");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamGroupInfo[] StreamGroupInfo(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamGroupInfo");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamInfo StreamInfo(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamInfo");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamPendingInfo StreamPending(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamPending");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamPendingMessageInfo[] StreamPendingMessages(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::System.Int32 @count, global::StackExchange.Redis.RedisValue @consumerName, global::System.Nullable<global::StackExchange.Redis.RedisValue> @minId, global::System.Nullable<global::StackExchange.Redis.RedisValue> @maxId, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamPendingMessages");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamPendingMessageInfo[] StreamPendingMessages(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::System.Int32 @count, global::StackExchange.Redis.RedisValue @consumerName, global::System.Nullable<global::StackExchange.Redis.RedisValue> @minId, global::System.Nullable<global::StackExchange.Redis.RedisValue> @maxId, global::System.Nullable<global::System.Int64> @minIdleTimeInMs, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamPendingMessages");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamTrimResult StreamAcknowledgeAndDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.StreamTrimMode @mode, global::StackExchange.Redis.RedisValue @messageId, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAcknowledgeAndDelete");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamTrimResult[] StreamAcknowledgeAndDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @groupName, global::StackExchange.Redis.StreamTrimMode @mode, global::StackExchange.Redis.RedisValue[] @messageIds, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamAcknowledgeAndDelete");
    /// <inheritdoc />
    public global::StackExchange.Redis.StreamTrimResult[] StreamDelete(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @messageIds, global::StackExchange.Redis.StreamTrimMode @mode, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamDelete");
    /// <inheritdoc />
    public global::StackExchange.Redis.StringIncrementResult<global::System.Double> StringIncrement(global::StackExchange.Redis.RedisKey @key, global::System.Double @value, global::StackExchange.Redis.Expiration @expiry, global::System.Nullable<global::System.Double> @lowerBound, global::System.Nullable<global::System.Double> @upperBound, global::StackExchange.Redis.IncrementOptions @options, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringIncrement");
    /// <inheritdoc />
    public global::StackExchange.Redis.StringIncrementResult<global::System.Int64> StringIncrement(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @value, global::StackExchange.Redis.Expiration @expiry, global::System.Nullable<global::System.Int64> @lowerBound, global::System.Nullable<global::System.Int64> @upperBound, global::StackExchange.Redis.IncrementOptions @options, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringIncrement");
    /// <inheritdoc />
    public global::System.Collections.Generic.IEnumerable<global::StackExchange.Redis.HashEntry> HashScan(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @pattern, global::System.Int32 @pageSize, global::System.Int64 @cursor, global::System.Int32 @pageOffset, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashScan");
    /// <inheritdoc />
    public global::System.Collections.Generic.IEnumerable<global::StackExchange.Redis.HashEntry> HashScan(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @pattern, global::System.Int32 @pageSize, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashScan");
    /// <inheritdoc />
    public global::System.Collections.Generic.IEnumerable<global::StackExchange.Redis.RedisValue> HashScanNoValues(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @pattern, global::System.Int32 @pageSize, global::System.Int64 @cursor, global::System.Int32 @pageOffset, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashScanNoValues");
    /// <inheritdoc />
    public global::System.Collections.Generic.IEnumerable<global::StackExchange.Redis.RedisValue> SetScan(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @pattern, global::System.Int32 @pageSize, global::System.Int64 @cursor, global::System.Int32 @pageOffset, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetScan");
    /// <inheritdoc />
    public global::System.Collections.Generic.IEnumerable<global::StackExchange.Redis.RedisValue> SetScan(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @pattern, global::System.Int32 @pageSize, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SetScan");
    /// <inheritdoc />
    public global::System.Collections.Generic.IEnumerable<global::StackExchange.Redis.RedisValue> VectorSetRangeEnumerate(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @start, global::StackExchange.Redis.RedisValue @end, global::System.Int64 @count, global::StackExchange.Redis.Exclude @exclude, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetRangeEnumerate");
    /// <inheritdoc />
    public global::System.Nullable<global::StackExchange.Redis.GeoPosition> GeoPosition(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoPosition");
    /// <inheritdoc />
    public global::System.Nullable<global::StackExchange.Redis.GeoPosition>[] GeoPosition(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @members, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoPosition");
    /// <inheritdoc />
    public global::System.Nullable<global::StackExchange.Redis.RedisArrayIndex> ArrayNext(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ArrayNext");
    /// <inheritdoc />
    public global::System.Nullable<global::StackExchange.Redis.SortedSetEntry> SortedSetPop(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.Order @order, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetPop");
    /// <inheritdoc />
    public global::System.Nullable<global::StackExchange.Redis.ValueCondition> StringDigest(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringDigest");
    /// <inheritdoc />
    public global::System.Nullable<global::StackExchange.Redis.VectorSetInfo> VectorSetInfo(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetInfo");
    /// <inheritdoc />
    public global::System.Nullable<global::System.DateTime> KeyExpireTime(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyExpireTime");
    /// <inheritdoc />
    public global::System.Nullable<global::System.Double> GeoDistance(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member1, global::StackExchange.Redis.RedisValue @member2, global::StackExchange.Redis.GeoUnit @unit, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoDistance");
    /// <inheritdoc />
    public global::System.Nullable<global::System.Double> SortedSetIncrement(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::System.Double @value, global::StackExchange.Redis.ValueCondition @when, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetIncrement");
    /// <inheritdoc />
    public global::System.Nullable<global::System.Double> SortedSetScore(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetScore");
    /// <inheritdoc />
    public global::System.Nullable<global::System.Double>[] SortedSetScores(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @members, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetScores");
    /// <inheritdoc />
    public global::System.Nullable<global::System.Int64> KeyFrequency(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyFrequency");
    /// <inheritdoc />
    public global::System.Nullable<global::System.Int64> KeyRefCount(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyRefCount");
    /// <inheritdoc />
    public global::System.Nullable<global::System.Int64> SortedSetRank(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.Order @order, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SortedSetRank");
    /// <inheritdoc />
    public global::System.Nullable<global::System.Int64> StringBitField(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.BitFieldOperation @operation, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringBitField");
    /// <inheritdoc />
    public global::System.Nullable<global::System.TimeSpan> KeyIdleTime(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyIdleTime");
    /// <inheritdoc />
    public global::System.String GeoHash(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoHash");
    /// <inheritdoc />
    public global::System.String KeyEncoding(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyEncoding");
    /// <inheritdoc />
    public global::System.String StringLongestCommonSubsequence(global::StackExchange.Redis.RedisKey @first, global::StackExchange.Redis.RedisKey @second, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StringLongestCommonSubsequence");
    /// <inheritdoc />
    public global::System.String VectorSetGetAttributesJson(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue @member, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("VectorSetGetAttributesJson");
    /// <inheritdoc />
    public global::System.String[] GeoHash(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.RedisValue[] @members, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("GeoHash");
    /// <inheritdoc />
    public global::System.TimeSpan Ping(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Ping");
    /// <inheritdoc />
    public void HashImport(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.HashImport @fieldSet, global::System.ReadOnlyMemory<global::StackExchange.Redis.RedisValue> @values, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HashImport");
    /// <inheritdoc />
    public void HyperLogLogMerge(global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisKey @first, global::StackExchange.Redis.RedisKey @second, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HyperLogLogMerge");
    /// <inheritdoc />
    public void HyperLogLogMerge(global::StackExchange.Redis.RedisKey @destination, global::StackExchange.Redis.RedisKey[] @sourceKeys, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HyperLogLogMerge");
    /// <inheritdoc />
    public void KeyMigrate(global::StackExchange.Redis.RedisKey @key, global::System.Net.EndPoint @toServer, global::System.Int32 @toDatabase, global::System.Int32 @timeoutMilliseconds, global::StackExchange.Redis.MigrateOptions @migrateOptions, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyMigrate");
    /// <inheritdoc />
    public void KeyRestore(global::StackExchange.Redis.RedisKey @key, global::System.Byte[] @value, global::System.Nullable<global::System.TimeSpan> @expiry, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeyRestore");
    /// <inheritdoc />
    public void ListSetByIndex(global::StackExchange.Redis.RedisKey @key, global::System.Int64 @index, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ListSetByIndex");
    /// <inheritdoc />
    public void StreamConfigure(global::StackExchange.Redis.RedisKey @key, global::StackExchange.Redis.StreamConfiguration @configuration, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("StreamConfigure");
}
