// <auto-generated />
// Run tools/Generate-StackExchangeCompat.ps1 after updating StackExchange.Redis.
#nullable disable
namespace Respire.StackExchangeCompat;
partial class CompatServer
{
    /// <inheritdoc />
    public global::System.Boolean HotKeysStop(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HotKeysStop");
    /// <inheritdoc />
    public global::System.Boolean ScriptExists(global::System.Byte[] @sha1, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptExists");
    /// <inheritdoc />
    public global::System.Boolean ScriptExists(global::System.String @script, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptExists");
    /// <inheritdoc />
    public global::System.Byte[] ScriptLoad(global::System.String @script, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptLoad");
    /// <inheritdoc />
    public global::System.Int64 ClientKill(global::StackExchange.Redis.ClientKillFilter @filter, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClientKill");
    /// <inheritdoc />
    public global::System.Int64 ClientKill(global::System.Nullable<global::System.Int64> @id, global::System.Nullable<global::StackExchange.Redis.ClientType> @clientType, global::System.Net.EndPoint @endpoint, global::System.Boolean @skipMe, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClientKill");
    /// <inheritdoc />
    public global::System.Int64 CommandCount(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("CommandCount");
    /// <inheritdoc />
    public global::System.Int64 DatabaseSize(global::System.Int32 @database, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("DatabaseSize");
    /// <inheritdoc />
    public global::System.Int64 LatencyReset(global::System.String[] @eventNames, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LatencyReset");
    /// <inheritdoc />
    public global::System.Int64 SubscriptionPatternCount(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SubscriptionPatternCount");
    /// <inheritdoc />
    public global::System.Int64 SubscriptionSubscriberCount(global::StackExchange.Redis.RedisChannel @channel, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SubscriptionSubscriberCount");
    /// <inheritdoc />
    public global::StackExchange.Redis.ClientInfo[] ClientList(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClientList");
    /// <inheritdoc />
    public global::StackExchange.Redis.ClusterConfiguration ClusterNodes(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClusterNodes");
    /// <inheritdoc />
    public global::StackExchange.Redis.ClusterSlotsResult ClusterSlots(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClusterSlots");
    /// <inheritdoc />
    public global::StackExchange.Redis.CommandTrace[] SlowlogGet(global::System.Int32 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SlowlogGet");
    /// <inheritdoc />
    public global::StackExchange.Redis.HotKeysResult HotKeysGet(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HotKeysGet");
    /// <inheritdoc />
    public global::StackExchange.Redis.LatencyHistoryEntry[] LatencyHistory(global::System.String @eventName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LatencyHistory");
    /// <inheritdoc />
    public global::StackExchange.Redis.LatencyLatestEntry[] LatencyLatest(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LatencyLatest");
    /// <inheritdoc />
    public global::StackExchange.Redis.LoadedLuaScript ScriptLoad(global::StackExchange.Redis.LuaScript @script, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptLoad");
    /// <inheritdoc />
    public global::StackExchange.Redis.ProductVariant GetProductVariant(out global::System.String @version)
        => throw Compatibility.Unsupported("GetProductVariant");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisChannel[] SubscriptionChannels(global::StackExchange.Redis.RedisChannel @pattern, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SubscriptionChannels");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisKey InventKey(global::StackExchange.Redis.RedisKey @prefix)
        => throw Compatibility.Unsupported("InventKey");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisKey[] CommandGetKeys(global::StackExchange.Redis.RedisValue[] @command, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("CommandGetKeys");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult Execute(global::System.Nullable<global::System.Int32> @database, global::System.String @command, global::System.Collections.Generic.ICollection<global::System.Object> @args, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Execute");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult Execute(global::System.String @command, global::System.Collections.Generic.ICollection<global::System.Object> @args, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Execute");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult Execute(global::System.String @command, global::System.Object[] @args)
        => throw Compatibility.Unsupported("Execute");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisResult MemoryStats(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("MemoryStats");
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisValue Echo(global::StackExchange.Redis.RedisValue @message, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Echo");
    /// <inheritdoc />
    public global::StackExchange.Redis.Role Role(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Role");
    /// <inheritdoc />
    public global::StackExchange.Redis.ServerCounters GetCounters()
        => throw Compatibility.Unsupported("GetCounters");
    /// <inheritdoc />
    public global::System.Collections.Generic.IAsyncEnumerable<global::StackExchange.Redis.RedisKey> KeysAsync(global::System.Int32 @database, global::StackExchange.Redis.RedisValue @pattern, global::System.Int32 @pageSize, global::System.Int64 @cursor, global::System.Int32 @pageOffset, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("KeysAsync");
    /// <inheritdoc />
    public global::System.Collections.Generic.IEnumerable<global::StackExchange.Redis.RedisKey> Keys(global::System.Int32 @database, global::StackExchange.Redis.RedisValue @pattern, global::System.Int32 @pageSize, global::System.Int64 @cursor, global::System.Int32 @pageOffset, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Keys");
    /// <inheritdoc />
    public global::System.Collections.Generic.IEnumerable<global::StackExchange.Redis.RedisKey> Keys(global::System.Int32 @database, global::StackExchange.Redis.RedisValue @pattern, global::System.Int32 @pageSize, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Keys");
    /// <inheritdoc />
    public global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[] ConfigGet(global::StackExchange.Redis.RedisValue @pattern, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ConfigGet");
    /// <inheritdoc />
    public global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[] SentinelMaster(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelMaster");
    /// <inheritdoc />
    public global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[][] SentinelMasters(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelMasters");
    /// <inheritdoc />
    public global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[][] SentinelReplicas(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelReplicas");
    /// <inheritdoc />
    public global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[][] SentinelSentinels(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelSentinels");
    /// <inheritdoc />
    public global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[][] SentinelSlaves(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelSlaves");
    /// <inheritdoc />
    public global::System.DateTime LastSave(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LastSave");
    /// <inheritdoc />
    public global::System.Linq.IGrouping<global::System.String, global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>>[] Info(global::StackExchange.Redis.RedisValue @section, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Info");
    /// <inheritdoc />
    public global::System.Net.EndPoint SentinelGetMasterAddressByName(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelGetMasterAddressByName");
    /// <inheritdoc />
    public global::System.Net.EndPoint[] SentinelGetReplicaAddresses(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelGetReplicaAddresses");
    /// <inheritdoc />
    public global::System.Net.EndPoint[] SentinelGetSentinelAddresses(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelGetSentinelAddresses");
    /// <inheritdoc />
    public global::System.String ClusterNodesRaw(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClusterNodesRaw");
    /// <inheritdoc />
    public global::System.String LatencyDoctor(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LatencyDoctor");
    /// <inheritdoc />
    public global::System.String MemoryAllocatorStats(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("MemoryAllocatorStats");
    /// <inheritdoc />
    public global::System.String MemoryDoctor(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("MemoryDoctor");
    /// <inheritdoc />
    public global::System.String[] CommandList(global::System.Nullable<global::StackExchange.Redis.RedisValue> @moduleName, global::System.Nullable<global::StackExchange.Redis.RedisValue> @category, global::System.Nullable<global::StackExchange.Redis.RedisValue> @pattern, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("CommandList");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task ClientKillAsync(global::System.Net.EndPoint @endpoint, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClientKillAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task ConfigResetStatisticsAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ConfigResetStatisticsAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task ConfigRewriteAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ConfigRewriteAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task ConfigSetAsync(global::StackExchange.Redis.RedisValue @setting, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ConfigSetAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task FlushAllDatabasesAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("FlushAllDatabasesAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task FlushDatabaseAsync(global::System.Int32 @database, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("FlushDatabaseAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task HotKeysResetAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HotKeysResetAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task HotKeysStartAsync(global::StackExchange.Redis.HotKeysMetrics @metrics, global::System.Int64 @count, global::System.TimeSpan @duration, global::System.Int64 @sampleRatio, global::System.Int32[] @slots, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HotKeysStartAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task MakePrimaryAsync(global::StackExchange.Redis.ReplicationChangeOptions @options, global::System.IO.TextWriter @log)
        => throw Compatibility.Unsupported("MakePrimaryAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task MemoryPurgeAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("MemoryPurgeAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task ReplicaOfAsync(global::System.Net.EndPoint @master, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ReplicaOfAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task SaveAsync(global::StackExchange.Redis.SaveType @type, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SaveAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task ScriptFlushAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptFlushAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task SentinelFailoverAsync(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelFailoverAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task SlaveOfAsync(global::System.Net.EndPoint @master, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SlaveOfAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task SlowlogResetAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SlowlogResetAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task SwapDatabasesAsync(global::System.Int32 @first, global::System.Int32 @second, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SwapDatabasesAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.ClientInfo[]> ClientListAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClientListAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.ClusterConfiguration> ClusterNodesAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClusterNodesAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.ClusterSlotsResult> ClusterSlotsAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClusterSlotsAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.CommandTrace[]> SlowlogGetAsync(global::System.Int32 @count, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SlowlogGetAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.HotKeysResult> HotKeysGetAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HotKeysGetAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.LatencyHistoryEntry[]> LatencyHistoryAsync(global::System.String @eventName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LatencyHistoryAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.LatencyLatestEntry[]> LatencyLatestAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LatencyLatestAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.LoadedLuaScript> ScriptLoadAsync(global::StackExchange.Redis.LuaScript @script, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptLoadAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.RedisChannel[]> SubscriptionChannelsAsync(global::StackExchange.Redis.RedisChannel @pattern, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SubscriptionChannelsAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.RedisKey[]> CommandGetKeysAsync(global::StackExchange.Redis.RedisValue[] @command, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("CommandGetKeysAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.RedisResult> ExecuteAsync(global::System.Nullable<global::System.Int32> @database, global::System.String @command, global::System.Collections.Generic.ICollection<global::System.Object> @args, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ExecuteAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.RedisResult> ExecuteAsync(global::System.String @command, global::System.Collections.Generic.ICollection<global::System.Object> @args, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ExecuteAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.RedisResult> ExecuteAsync(global::System.String @command, global::System.Object[] @args)
        => throw Compatibility.Unsupported("ExecuteAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.RedisResult> MemoryStatsAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("MemoryStatsAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.RedisValue> EchoAsync(global::StackExchange.Redis.RedisValue @message, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("EchoAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::StackExchange.Redis.Role> RoleAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("RoleAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Boolean> HotKeysStopAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HotKeysStopAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Boolean> ScriptExistsAsync(global::System.Byte[] @sha1, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptExistsAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Boolean> ScriptExistsAsync(global::System.String @script, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptExistsAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Byte[]> ScriptLoadAsync(global::System.String @script, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptLoadAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[][]> SentinelMastersAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelMastersAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[][]> SentinelReplicasAsync(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelReplicasAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[][]> SentinelSentinelsAsync(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelSentinelsAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[][]> SentinelSlavesAsync(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelSlavesAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[]> ConfigGetAsync(global::StackExchange.Redis.RedisValue @pattern, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ConfigGetAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>[]> SentinelMasterAsync(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelMasterAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.DateTime> LastSaveAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LastSaveAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Int64> ClientKillAsync(global::StackExchange.Redis.ClientKillFilter @filter, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClientKillAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Int64> ClientKillAsync(global::System.Nullable<global::System.Int64> @id, global::System.Nullable<global::StackExchange.Redis.ClientType> @clientType, global::System.Net.EndPoint @endpoint, global::System.Boolean @skipMe, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClientKillAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Int64> CommandCountAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("CommandCountAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Int64> DatabaseSizeAsync(global::System.Int32 @database, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("DatabaseSizeAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Int64> LatencyResetAsync(global::System.String[] @eventNames, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LatencyResetAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Int64> SubscriptionPatternCountAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SubscriptionPatternCountAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Int64> SubscriptionSubscriberCountAsync(global::StackExchange.Redis.RedisChannel @channel, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SubscriptionSubscriberCountAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Linq.IGrouping<global::System.String, global::System.Collections.Generic.KeyValuePair<global::System.String, global::System.String>>[]> InfoAsync(global::StackExchange.Redis.RedisValue @section, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("InfoAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Net.EndPoint[]> SentinelGetReplicaAddressesAsync(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelGetReplicaAddressesAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Net.EndPoint[]> SentinelGetSentinelAddressesAsync(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelGetSentinelAddressesAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Net.EndPoint> SentinelGetMasterAddressByNameAsync(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelGetMasterAddressByNameAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.String[]> CommandListAsync(global::System.Nullable<global::StackExchange.Redis.RedisValue> @moduleName, global::System.Nullable<global::StackExchange.Redis.RedisValue> @category, global::System.Nullable<global::StackExchange.Redis.RedisValue> @pattern, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("CommandListAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.String> ClusterNodesRawAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClusterNodesRawAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.String> LatencyDoctorAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("LatencyDoctorAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.String> MemoryAllocatorStatsAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("MemoryAllocatorStatsAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.String> MemoryDoctorAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("MemoryDoctorAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.TimeSpan> PingAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("PingAsync");
    /// <inheritdoc />
    public global::System.TimeSpan Ping(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Ping");
    /// <inheritdoc />
    public void ClientKill(global::System.Net.EndPoint @endpoint, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ClientKill");
    /// <inheritdoc />
    public void ConfigResetStatistics(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ConfigResetStatistics");
    /// <inheritdoc />
    public void ConfigRewrite(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ConfigRewrite");
    /// <inheritdoc />
    public void ConfigSet(global::StackExchange.Redis.RedisValue @setting, global::StackExchange.Redis.RedisValue @value, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ConfigSet");
    /// <inheritdoc />
    public void FlushAllDatabases(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("FlushAllDatabases");
    /// <inheritdoc />
    public void FlushDatabase(global::System.Int32 @database, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("FlushDatabase");
    /// <inheritdoc />
    public void HotKeysReset(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HotKeysReset");
    /// <inheritdoc />
    public void HotKeysStart(global::StackExchange.Redis.HotKeysMetrics @metrics, global::System.Int64 @count, global::System.TimeSpan @duration, global::System.Int64 @sampleRatio, global::System.Int32[] @slots, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("HotKeysStart");
    /// <inheritdoc />
    public void MakeMaster(global::StackExchange.Redis.ReplicationChangeOptions @options, global::System.IO.TextWriter @log)
        => throw Compatibility.Unsupported("MakeMaster");
    /// <inheritdoc />
    public void MemoryPurge(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("MemoryPurge");
    /// <inheritdoc />
    public void ReplicaOf(global::System.Net.EndPoint @master, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ReplicaOf");
    /// <inheritdoc />
    public void Save(global::StackExchange.Redis.SaveType @type, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Save");
    /// <inheritdoc />
    public void ScriptFlush(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("ScriptFlush");
    /// <inheritdoc />
    public void SentinelFailover(global::System.String @serviceName, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SentinelFailover");
    /// <inheritdoc />
    public void Shutdown(global::StackExchange.Redis.ShutdownMode @shutdownMode, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Shutdown");
    /// <inheritdoc />
    public void SlaveOf(global::System.Net.EndPoint @master, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SlaveOf");
    /// <inheritdoc />
    public void SlowlogReset(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SlowlogReset");
    /// <inheritdoc />
    public void SwapDatabases(global::System.Int32 @first, global::System.Int32 @second, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("SwapDatabases");
    /// <inheritdoc />
    public global::System.Boolean AllowReplicaWrites { get => throw Compatibility.Unsupported("AllowReplicaWrites"); set => throw Compatibility.Unsupported("AllowReplicaWrites"); }
    /// <inheritdoc />
    public global::System.Boolean AllowSlaveWrites { get => throw Compatibility.Unsupported("AllowSlaveWrites"); set => throw Compatibility.Unsupported("AllowSlaveWrites"); }
    /// <inheritdoc />
    public global::StackExchange.Redis.ClusterConfiguration ClusterConfiguration { get => throw Compatibility.Unsupported("ClusterConfiguration"); }
    /// <inheritdoc />
    public global::System.Int32 DatabaseCount { get => throw Compatibility.Unsupported("DatabaseCount"); }
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisFeatures Features { get => throw Compatibility.Unsupported("Features"); }
    /// <inheritdoc />
    public global::System.Boolean IsSlave { get => throw Compatibility.Unsupported("IsSlave"); }
    /// <inheritdoc />
    public global::StackExchange.Redis.RedisProtocol Protocol { get => throw Compatibility.Unsupported("Protocol"); }
    /// <inheritdoc />
    public global::StackExchange.Redis.ServerType ServerType { get => throw Compatibility.Unsupported("ServerType"); }
    /// <inheritdoc />
    public global::System.Version Version { get => throw Compatibility.Unsupported("Version"); }
}
