// <auto-generated />
// Run tools/Generate-StackExchangeCompat.ps1 after updating StackExchange.Redis.
#nullable disable
namespace Respire.StackExchangeCompat;
partial class CompatSubscriber
{
    /// <inheritdoc />
    public global::System.Boolean IsConnected(global::StackExchange.Redis.RedisChannel @channel)
        => throw Compatibility.Unsupported("IsConnected");
    /// <inheritdoc />
    public global::System.Net.EndPoint IdentifyEndpoint(global::StackExchange.Redis.RedisChannel @channel, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("IdentifyEndpoint");
    /// <inheritdoc />
    public global::System.Net.EndPoint SubscribedEndpoint(global::StackExchange.Redis.RedisChannel @channel)
        => throw Compatibility.Unsupported("SubscribedEndpoint");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Net.EndPoint> IdentifyEndpointAsync(global::StackExchange.Redis.RedisChannel @channel, global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("IdentifyEndpointAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.TimeSpan> PingAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("PingAsync");
    /// <inheritdoc />
    public global::System.TimeSpan Ping(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("Ping");
}
