// <auto-generated />
// Run tools/Generate-StackExchangeCompat.ps1 after updating StackExchange.Redis.
#nullable disable
namespace Respire.StackExchangeCompat;
partial class RespireConnectionMultiplexer
{
    /// <inheritdoc />
    public global::System.Boolean Configure(global::System.IO.TextWriter @log)
        => throw Compatibility.Unsupported("Configure");
    /// <inheritdoc />
    public global::System.Int32 GetHashSlot(global::StackExchange.Redis.RedisKey @key)
        => throw Compatibility.Unsupported("GetHashSlot");
    /// <inheritdoc />
    public global::System.Int32 HashSlot(global::StackExchange.Redis.RedisKey @key)
        => throw Compatibility.Unsupported("HashSlot");
    /// <inheritdoc />
    public global::System.Int64 PublishReconfigure(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("PublishReconfigure");
    /// <inheritdoc />
    public global::StackExchange.Redis.ServerCounters GetCounters()
        => throw Compatibility.Unsupported("GetCounters");
    /// <inheritdoc />
    public global::System.String GetStatus()
        => throw Compatibility.Unsupported("GetStatus");
    /// <inheritdoc />
    public global::System.String GetStormLog()
        => throw Compatibility.Unsupported("GetStormLog");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Boolean> ConfigureAsync(global::System.IO.TextWriter @log)
        => throw Compatibility.Unsupported("ConfigureAsync");
    /// <inheritdoc />
    public global::System.Threading.Tasks.Task<global::System.Int64> PublishReconfigureAsync(global::StackExchange.Redis.CommandFlags @flags)
        => throw Compatibility.Unsupported("PublishReconfigureAsync");
    /// <inheritdoc />
    public void AddLibraryNameSuffix(global::System.String @suffix)
        => throw Compatibility.Unsupported("AddLibraryNameSuffix");
    /// <inheritdoc />
    public void ExportConfiguration(global::System.IO.Stream @destination, global::StackExchange.Redis.ExportOptions @options)
        => throw Compatibility.Unsupported("ExportConfiguration");
    /// <inheritdoc />
    public void GetStatus(global::System.IO.TextWriter @log)
        => throw Compatibility.Unsupported("GetStatus");
    /// <inheritdoc />
    public void RegisterProfiler(global::System.Func<global::StackExchange.Redis.Profiling.ProfilingSession> @profilingSessionProvider)
        => throw Compatibility.Unsupported("RegisterProfiler");
    /// <inheritdoc />
    public void ResetStormLog()
        => throw Compatibility.Unsupported("ResetStormLog");
    /// <inheritdoc />
    public global::System.Boolean IncludeDetailInExceptions { get => throw Compatibility.Unsupported("IncludeDetailInExceptions"); set => throw Compatibility.Unsupported("IncludeDetailInExceptions"); }
    /// <inheritdoc />
    public global::System.Boolean IsConnecting { get => throw Compatibility.Unsupported("IsConnecting"); }
    /// <inheritdoc />
    public global::System.Int64 OperationCount { get => throw Compatibility.Unsupported("OperationCount"); }
    /// <inheritdoc />
    public global::System.Boolean PreserveAsyncOrder { get => throw Compatibility.Unsupported("PreserveAsyncOrder"); set => throw Compatibility.Unsupported("PreserveAsyncOrder"); }
    /// <inheritdoc />
    public global::System.Int32 StormLogThreshold { get => throw Compatibility.Unsupported("StormLogThreshold"); set => throw Compatibility.Unsupported("StormLogThreshold"); }
    /// <inheritdoc />
    public event global::System.EventHandler<global::StackExchange.Redis.EndPointEventArgs> ConfigurationChanged { add => throw Compatibility.Unsupported("ConfigurationChanged"); remove => throw Compatibility.Unsupported("ConfigurationChanged"); }
    /// <inheritdoc />
    public event global::System.EventHandler<global::StackExchange.Redis.EndPointEventArgs> ConfigurationChangedBroadcast { add => throw Compatibility.Unsupported("ConfigurationChangedBroadcast"); remove => throw Compatibility.Unsupported("ConfigurationChangedBroadcast"); }
    /// <inheritdoc />
    public event global::System.EventHandler<global::StackExchange.Redis.ConnectionFailedEventArgs> ConnectionFailed { add => throw Compatibility.Unsupported("ConnectionFailed"); remove => throw Compatibility.Unsupported("ConnectionFailed"); }
    /// <inheritdoc />
    public event global::System.EventHandler<global::StackExchange.Redis.ConnectionFailedEventArgs> ConnectionRestored { add => throw Compatibility.Unsupported("ConnectionRestored"); remove => throw Compatibility.Unsupported("ConnectionRestored"); }
    /// <inheritdoc />
    public event global::System.EventHandler<global::StackExchange.Redis.RedisErrorEventArgs> ErrorMessage { add => throw Compatibility.Unsupported("ErrorMessage"); remove => throw Compatibility.Unsupported("ErrorMessage"); }
    /// <inheritdoc />
    public event global::System.EventHandler<global::StackExchange.Redis.HashSlotMovedEventArgs> HashSlotMoved { add => throw Compatibility.Unsupported("HashSlotMoved"); remove => throw Compatibility.Unsupported("HashSlotMoved"); }
    /// <inheritdoc />
    public event global::System.EventHandler<global::StackExchange.Redis.InternalErrorEventArgs> InternalError { add => throw Compatibility.Unsupported("InternalError"); remove => throw Compatibility.Unsupported("InternalError"); }
    /// <inheritdoc />
    public event global::System.EventHandler<global::StackExchange.Redis.Maintenance.ServerMaintenanceEvent> ServerMaintenanceEvent { add => throw Compatibility.Unsupported("ServerMaintenanceEvent"); remove => throw Compatibility.Unsupported("ServerMaintenanceEvent"); }
}
