param(
    [string]$AssemblyPath = "$env:USERPROFILE/.nuget/packages/stackexchange.redis/3.3.1/lib/net10.0/StackExchange.Redis.dll"
)

$ErrorActionPreference = 'Stop'
$packageRoot = Split-Path (Split-Path (Split-Path (Split-Path (Split-Path $AssemblyPath))))
[void][Reflection.Assembly]::LoadFrom((Join-Path $packageRoot 'respite/3.3.1/lib/net10.0/RESPite.dll'))
$assembly = [Reflection.Assembly]::LoadFrom((Resolve-Path $AssemblyPath))
function Format-Type([Type]$type) {
    if ($type.IsGenericParameter) { return $type.Name }
    if ($type.IsArray) { return (Format-Type $type.GetElementType()) + '[]' }
    if ($type.IsByRef) { return (Format-Type $type.GetElementType()) }
    if ($type -eq [void]) { return 'void' }
    if ($type.IsGenericType) {
        $name = $type.GetGenericTypeDefinition().FullName -replace '`\d+', '' -replace '\+', '.'
        return 'global::' + $name + '<' + (($type.GetGenericArguments() | ForEach-Object { Format-Type $_ }) -join ', ') + '>'
    }
    return 'global::' + ($type.FullName -replace '\+', '.')
}

function Generate-Class($className, $interfaceNames, $excluded) {
    $lines = [Collections.Generic.List[string]]::new()
    $lines.Add('// <auto-generated />')
    $lines.Add('// Run tools/Generate-StackExchangeCompat.ps1 after updating StackExchange.Redis.')
    $lines.Add('#nullable disable')
    $lines.Add('namespace Respire.StackExchangeCompat;')
    $lines.Add("partial class $className")
    $lines.Add('{')
    $types = foreach ($name in $interfaceNames) { $assembly.GetType("StackExchange.Redis.$name") }
    $methods = $types.GetMethods() | Sort-Object { $_.ToString() } -Unique
    foreach ($method in $methods) {
        if ($method.IsSpecialName -or $method.Name -in $excluded) { continue }
        $parameters = $method.GetParameters() | ForEach-Object {
            $modifier = if ($_.IsOut) { 'out ' } elseif ($_.ParameterType.IsByRef) { 'ref ' } else { '' }
            $modifier + (Format-Type $_.ParameterType) + ' @' + $_.Name
        }
        $generics = if ($method.IsGenericMethod) { '<' + ($method.GetGenericArguments().Name -join ', ') + '>' } else { '' }
        $hide = if ($className -eq 'CompatDatabase' -and $method.Name -eq 'CreateTransaction') { 'new ' } else { '' }
        $lines.Add('    /// <inheritdoc />')
        $lines.Add('    public ' + $hide + (Format-Type $method.ReturnType) + ' ' + $method.Name + $generics + '(' + ($parameters -join ', ') + ')')
        $lines.Add('        => throw Compatibility.Unsupported("' + $method.Name + '");')
    }
    foreach ($property in ($types.GetProperties() | Sort-Object Name -Unique)) {
        if ($property.Name -in $excluded) { continue }
        $accessors = @()
        if ($property.CanRead) { $accessors += 'get => throw Compatibility.Unsupported("' + $property.Name + '");' }
        if ($property.CanWrite) { $accessors += 'set => throw Compatibility.Unsupported("' + $property.Name + '");' }
        $lines.Add('    /// <inheritdoc />')
        $lines.Add('    public ' + (Format-Type $property.PropertyType) + ' ' + $property.Name + ' { ' + ($accessors -join ' ') + ' }')
    }
    foreach ($event in ($types.GetEvents() | Sort-Object Name -Unique)) {
        $lines.Add('    /// <inheritdoc />')
        $lines.Add('    public event ' + (Format-Type $event.EventHandlerType) + ' ' + $event.Name + ' { add => throw Compatibility.Unsupported("' + $event.Name + '"); remove => throw Compatibility.Unsupported("' + $event.Name + '"); }')
    }
    $lines.Add('}')
    [IO.File]::WriteAllLines((Join-Path $PSScriptRoot "../src/Respire.StackExchangeCompat/$className.Unsupported.g.cs"), $lines)
}

$hashList = @('HashGetAll', 'HashLength', 'HashDelete', 'ListLength', 'ListGetByIndex', 'ListLeftPush', 'ListRemove', 'ListTrim', 'ListRightPopLeftPush')
$async = @('HashGetAsync', 'HashGetLeaseAsync', 'HashSetAsync', 'KeyExpireAsync', 'KeyDeleteAsync', 'ListRangeAsync', 'ListRightPushAsync', 'Database', 'Multiplexer', 'Wait', 'WaitAll', 'TryWait') + @($hashList | ForEach-Object { $_ + 'Async' })
Generate-Class 'CompatDatabaseAsync' @('IDatabaseAsync', 'IRedisAsync') $async
Generate-Class 'CompatDatabase' @('IDatabase', 'IRedis') (@('HashGet', 'HashGetLease', 'HashSet', 'KeyExpire', 'KeyDelete', 'ListRange', 'ListRightPush', 'CreateBatch', 'Database', 'Wait', 'WaitAll') + $hashList)
Generate-Class 'RespireConnectionMultiplexer' @('IConnectionMultiplexer') @('GetDatabase', 'Close', 'CloseAsync', 'Wait', 'WaitAll', 'ClientName', 'Configuration', 'TimeoutMilliseconds', 'IsConnected', 'ToString')
