/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    'getting-started',
    'packages',
    'stackexchange-redis',
    'fundamentals/client-side-caching',
    {
      type: 'category',
      label: 'Core concepts',
      items: [
        'fundamentals/connections',
        'fundamentals/values-and-serialization',
      ],
    },
    {
      type: 'category',
      label: 'Commands',
      items: ['commands/strings-and-keys', 'commands/collections', 'commands/arrays'],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/testing-containers',
        'guides/testing-sample',
        'guides/distributed-locks',
        'guides/failover-groups',
        'guides/coordination',
        'guides/blocking-queues',
        'guides/vector-sets',
        'guides/json',
        'guides/search',
        'guides/timeseries',
        'guides/probabilistic',
        'guides/reconnect-policy',
        'guides/renewable-credentials',
        'guides/aws-iam-credentials',
        'guides/azure-managed-redis',
        'guides/pub-sub',
        'guides/keyspace-notifications',
        'guides/pub-sub-introspection',
        'guides/client-administration',
        'guides/acl-administration',
        'guides/server-metadata-and-persistence',
        'guides/server-diagnostics',
        'guides/cluster-inspection',
        'guides/command-logs',
        'guides/hot-keys',
        'guides/value-codecs',
        'guides/in-memory-testing',
        'guides/batches-and-transactions',
        'guides/hash-import',
        'guides/durability-acknowledgements',
        'guides/raw-commands',
        'guides/generated-commands',
        'guides/server-extensions',
        'guides/deferred-raw-commands',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: ['integrations/dependency-injection', 'integrations/caching', 'integrations/observability'],
    },
    'performance',
    'benchmarks',
    'stress-tests',
    'roadmap',
  ],
};

export default sidebars;
